<?php
return array_merge([

    // Responses
    'created_response' => ':name ကိုအောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။',
    'updated_response' => ':name ကိုအောင်မြင်စွာ ပြောင်းလဲ(update)ပြီးပါပြီ။',
    'deleted_response' => ':name ကိုအောင်မြင်စွာ ဖျက်သိမ်းပြီးပါပြီ။',
    'failed_response' => 'တစ်ခုခုမှားယွင်းခဲ့ပါသည်။',
    'notified' => ':name ကိုအောင်မြင်စွာ အကြောင်းကြားပြီးပါပြီ။',
    'duplicated_response' => ':name ကိုအောင်မြင်စွာ ပွားပြီးပါပြီ။',
    'status_updated_response' => ':name အခြေအနေကို :status သို့ပြောင်းလဲ(update)ပြီးပါပြီ။',
    'action_not_allowed' => 'ဤလုပ်ဆောင်ချက်အတွက် သင့်အား ခွင့်ပြုမထားပါ။',
    'cant_delete_own_account' => 'သင်၏ကိုယ်ပိုင် အကောင့်ကို ဖျက်သိမ်း၍မရပါ။',
    'attached_response' => ':name ကို အောင်မြင်စွာ ပူးတွဲပြီးပါပြီ။',
    'detached_response' => ':name ကို အောင်မြင်စွာ ခွဲထုတ်ပြီးပါပြီ။',
    'default_delete' => 'သင်၏ မူရင်း:name . ကို ဖျက်၍မရပါ။',
    'default_update' => 'သင်၏ မူရင်း :name ကို ပြောင်းလဲ၍မရပါ။',
    'old_password_is_in_correct' => 'စကားဝှက်ဟောင်း မမှန်ကန်ပါ။',
    'attach_log' => ':pivot အသစ်ကို :model နှင့်တွဲထားပါသည်။',
    'detach_log' => ':pivot ကို :model မှခွဲထုတ်ထားပါသည်။',
    'status_log' => ':model ကို :status ပြီးပါပြီ။',
    'incorrect_user_password' => 'အသုံးပြုသူ သို့မဟုတ် စကားဝှက်မမှန်ကန်ပါ။',
    'invite_user_response' => 'အသုံးပြုသူကို အောင်မြင်စွာ ဖိတ်ကြားပြီးပါပြီ။',
    'invalid_token' => 'Token သည် မမှန်ကန်ပါ။',
    'user_account_confirmed' => 'သင့်အကောင့်ကို အောင်မြင်စွာ အတည်ပြုပြီးပါပြီ။',
    'user_invited_to_join' => 'အသုံးပြုသူကို အောင်မြင်စွာ ဖိတ်ကြားထားပြီးပါပြီ။',
    'user_confirm_joining' => 'အသုံးပြုသူသည် သူ၏ပါဝင်ခြင်းကို အတည်ပြုခဲ့ပါသည်။',
    'log_description_message' => ':model ကို :event ပြီးပါပြီ။',
    'password_reset_mail_has_been_sent_successfully' => 'ပြန်လည်သတ်မှတ်ထားသော စကားဝှက်လင့်ခ်ပါသည့် အီးမေလ်းတစ်စောင်ကို သင်၏အီးမေလ်းလိပ်စာသို့ ကျွန်တော်တို့ပို့ခဲ့ပါသည်။ ကျေးဇူးပြု၍စစ်ဆေးပေးပါ။',
    'no_user_found_on_that_email' => 'ထိုအီးမေးလ်လိပ်စာကို အသုံးပြုသူ မတွေ့ပါ။.',
    'password_has_been_reset_successfully' => 'သင့်စကားဝှက်ကို အောင်မြင်စွာ ပြန်လည်သတ်မှတ်ပြီးပါပြီ။',
    'resource_not_found' => 'သင်ရှာဖွေနေသော :resource ကို ရှာမတွေ့ပါ။',
    'created' => 'ဖန်တီးပြီးပါပြီ။',
    'deleted' => 'ဖျက်သိမ်းပြီးသွားပါပြီ။',
    'updated' => 'ပြောင်းလဲ(update)ပြီးပါပြီ။',
    'resource' => 'မူလအရင်းအမြစ်',

    // Number of Decimal
    '0' => 'သုည(၀)',

    // HTTP Responses
    '200' => 'အောင်မြင်သည်။',
    '2' => 'နှစ်(၂)',
    '400' => 'တောင်းဆိုမှုမှားယွင်းနေသည်။',
    '401' => 'ခွင့်ပြုမထားပါ။',
    '403' => 'တားမြစ်ထားသည်။',
    '404' => 'ရှာမတွေ့ပါ။',
    '413' => 'သင်၏ request သည် server လက်ခံနိုင်သောအရွယ်အစားထက်ပိုကြီးနေပါသည်။',
    '414' => 'URI ရှည်လွန်းနေပါသည်။',
    '415' => 'ပံ့ပိုးမထားသော မီဒီယာအမျိုးအစား',
    '426' => 'အဆင့်မြှင့်တင်ရန် လိုအပ်သည်။',
    '429' => 'requestများ အလွန်များနေပါသည်။',
    'tenant_invitation_cant_be_canceled' => 'အငှား ဖိတ်ခေါ်ထားမှသာလျှင် အငှားဖိတ်ကြားချက်ကို ပယ်ဖျက်နိုင်သည်၊',
    'tenant_invitation_has_benn_canceled_successfully' => 'အငှားကို အောင်မြင်စွာ ပယ်ဖျက်လိုက်ပါပြီ။',

    // Custom Field Builder
    'custom_field' => 'စိတ်ကြိုက်အကွက်',
    'custom_field_type' => 'စိတ်ကြိုက်အကွက် အမျိုးအစား',
    'phone_number_field_is_required' => 'ဖုန်းနံပါတ်အကွက် လိုအပ်ပါသည်။',
    'email_field_is_required' => 'အီးမေးလ်အကွက် လိုအပ်သည်။',
    'email_has_taken' => 'အီးမေလ်းယူထားပြီးပါပြီ။',

    // Fields
    'text' => 'စာတိုက်ပုံး',
    'textarea' => 'စာသားဧရိယာ',
    'checkbox' => 'အမှတ်ခြစ်ပါ။',
    'radio_button' => 'ရေဒီယို ခလုတ်',
    'radio' => 'ရေဒီယို',
    'select' => 'ရွေးချယ်ပါ။',
    'multi_select' => 'မျိုးစုံရွေးချယ်ပါ။',
    'did_not_match_anything' => "မည်သည့်အရာမှမကိုက်ညီပါ။",
    'enter_to_add_new' => 'အသစ်ထည့်ရန် ဝင်ပါ။',
    'no_options_found' => 'ရွေးချယ်စရာမတွေ့ပါ။',
    'pick_a_color' => 'အရောင်တစ်ခုရွေးပါ။',

    // Notification event
    'notification_events' => 'အကြောင်းကြားသည့်အခြေအနေများ',
    'notification_event_name' => ':name :action',
    'notification_created' => 'ဖန်တီးပြီးပါပြီ။',
    'notification_updated' => 'ပြောင်းလဲ(update)ပြီးပါပြီ။',
    'notification_deleted' => 'ဖျက်သိမ်းပြီးသွားပါပြီ။',
    'notification_user' => 'အသုံးပြုသူ',
    'notification_reset' => 'ပြန်လည်သတ်မှတ်ပါ။',
    'notification_invitation' => 'ဖိတ်ကြားချက်',
    'notification_joined' => 'ပါဝင်ခဲ့ပါသည်။',
    'notification_' => ' ',
    'notification_canceled' => 'ပယ်ဖျက်ခဲ့ပါသည်။',
    'notification_invited' => 'ဖိတ်ခေါ်ခဲ့ပါသည်။',
    'password-reset' => 'စကားဝှက်ပြန်လည်သတ်မှတ်လိုက်ပါပြီ။',
    'notification_activation' => 'ပါဝင်ခြင်း။',

    // Notifications
    'notification' => 'အသိပေးချက်',
    'notify_by_email' => 'အီးမေးလ်ဖြင့်အကြောင်းကြားပါ။',
    'notify_by_sms' => 'SMS ဖြင့်အကြောင်းကြားပါ။',
    'notification_settings' => 'အကြောင်းကြားချက် ဆက်တင်များ',
    'notification_template' => 'အသိပေးချက်ပုံစံ',

    // Labels
    'user' => 'အသုံးပြုသူ',
    'brand' => 'အမှတ်တံဆိပ်',
    'status' => 'အခြေအနေ',
    'name' => 'နာမည်',
    'email' => 'အီးမေလ်း',
    'mail' => 'မေးလ်',
    'value' => 'တန်ဖိုး',
    'type' => 'စာရိုက်ပါ။',
    'database' => 'စနစ်',
    'sms' => 'SMS',
    'users' => 'အသုံးပြုသူများ',
    'add_users' => 'အသုံးပြုသူများကို ထည့်ပါ',
    'manage_users' => 'အသုံးပြုသူများကို စီမံခန့်ခွဲပါ။',
    'roles' => 'ရာထူးတာဝန်များ',
    'role' => 'အခန်းကဏ္ဍ',
    'permissions' => 'ခွင့်ပြုချက်များ',
    'permission' => 'ခွင့်ပြုချက်',
    'settings' => 'ဆက်တင်များ',
    'password' => 'စကားဝှက်',
    'show_password' => 'စကားဝှက်ကိုပြပါ။',
    'hide_password' => 'စကားဝှက်ကို ဝှက်ထားပါ။',
    'allowed' => 'ခွင့်ပြုထားသော',
    'profile_picture' => 'ပရိုဖိုင်ပုံ',
    'delivery_settings' => 'အီးမေလ်း ဆက်တင်များ',
    'brand_settings' => 'အမှတ်တံဆိပ် ဆက်တင်များ',
    'privacy_settings' => 'ကိုယ်ရေးကိုယ်တာ ဆက်တင်များ',
    'corn_job' => 'Corn job', 
    'brand_group' => 'အမှတ်တံဆိပ်အုပ်စု',
    'template' => 'ပုံစံခွက်',
    'profile' => 'ကိုယ်ရေးအကျဉ်း',
    'log' => 'မှတ်တမ်း',
    'invite' => 'ဖိတ်ခေါ်ချက်',
    'users_roles' => 'အသုံးပြုသူများနှင့် ရာထူးများ',
    'my_profile' => 'ကျွန်ုပ်၏ ကိုယ်ရေးအကျဉ်း',
    'dashboard' => 'ဒက်ရှ်ဘုတ်(dashboard)',
    'recent_sales' => 'လတ်တလော ရောင်းအား',
    'top_customer' => 'ထိပ်တန်းဝယ်ယူသူ',
    'notifications' => 'အသိပေးချက်များ',
    'log_out' => 'အကောင့်မှ ထွက်ပါ',
    'tenant_group' => 'အငှားအဖွဲ့',
    "all_tenants" => "အငှားအားလုံး",
    'group' => 'အဖွဲ့',
    'cancel' => 'ပယ်ဖျက်သည်။',
    'upload' => 'တင်သည်။',
    'submit' => 'တင်ပြပါ။',
    'first' => 'ပထမ',
    'last' => 'နောက်ဆုံး',
    'app' => 'အက်ပ်(app)',
    'language' => 'ဘာသာစကား',
    'date' => 'ရက်စွဲ',
    'format' => 'ပုံစံ',
    'time' => 'အချိန်',
    'zone' => 'ဇုန်',
    'number' => 'နံပါတ်',
    'decimal' => 'ဒဿမ',
    'separator' => 'ခွဲထုတ်ခြင်း',
    'thousand' => 'နံပါတ်',
    'date_and_time' => 'ရက်စွဲ နှင့် အချိန်',
    'app_info' => 'အက်ပ်(app)အချက်အလက်',
    "recommended_app_logo_size" => "(အကြံပြုထားသောအရွယ်အစား: 135 x 55 px)",
    "recommended_app_icon_size" => "(အကြံပြုထားသောအရွယ်အစား: 70 x 70 px)",
    "recommended_app_banner_size" => "(အကြံပြုထားသောအရွယ်အစား: 1920 x 100 px)",
    'd-m-Y' => 'DD-MM-YYYY',
    'm-d-Y' => 'MM-DD-YYYY',
    'Y-m-d' => 'YYYY-MM-DD',
    'm/d/Y' => 'MM/DD/YYYY',
    'd/m/Y' => 'DD/MM/YYYY',
    'Y/m/d' => 'YYYY/MM/DD',
    'm.d.Y' => 'MM.DD.YYYY',
    'd.m.Y' => 'DD.MM.YYYY',
    'Y.m.d' => 'YYYY.MM.DD',
    'update' => 'ပြောင်းလဲ(update)သည်',
    'templates' => 'ပုံစံများ',
    'channel' => 'ချန်နယ်',
    'tenantGroup' => 'အငှားအဖွဲ့',
    'no_delivery_settings_found' => 'အီးမေးလ်ဆက်တင်များ မတွေ့ပါ။',
    'no_delivery_settings_warning' => 'ဖိတ်ကြားချက်ပေးပို့ရန် အီးမေးလ်ဆက်တင်များကို ထည့်သွင်းရပါမည်။ အီးမေးလ်ဆက်တင်များထည့်ရန် {location} ကိုနှိပ်ပါ။',
    'pos_menu_no_email_setting_warning' => 'အရောင်းမြှင့်တင်ရန်အတွက် သင်သည် အီးမေးလ်ဆက်တင်များကို သတ်မှတ်ရပါမည်။ အီးမေးလ်ဆက်တင်များထည့်ရန် {location} ကိုနှိပ်ပါ။',
    'test_email' => 'အီးမေးလ်ကို စစ်ဆေးပါ။',
    'send_test_email' => 'စစ်ဆေးသည့် အီးမေးလ်ကိုပို့ပါ။',
    'email_sent_successfully' => 'အီးမေးလ်ကို အောင်မြင်စွာ ပေးပို့ခဲ့ပါသည်။',
    'email_setup_is_not_correct' => 'အီးမေးလ် စနစ်ထည့်သွင်းမှု မမှန်ကန်ပါ။',
    'here' => 'ဤနေရာ',
    'notification_form' => 'အကြောင်းကြားဖောင်(form)',
    'event' => 'ဖြစ်စဉ်များ',
    'tenant_admin_email' => 'အငှား admin အီးမေလ်း',
    'email_setup' => 'အီးမေးလ် စနစ်ထည့်သွင်းခြင်း။',
    'sales_invoice_setup' => 'အရောင်းပြေစာ စနစ်ထည့်သွင်းခြင်း။',
    'return_invoice_setup' => 'ပြေစာပြန်ပေးသည့် စနစ်ထည့်သွင်းခြင်း။',
    'no_items_left_to_return' => 'အကြောင်းပြန်ရန် ပစ္စည်းမကျန်တော့ပါ။',
    'invoice_prefix' => 'ပြေစာရှေ့ဆက်တွဲ',
    'invoice_suffix' => 'ပြေစာနောက်ဆက်တွဲ',
    'invoice_already_configured' => "ငွေတောင်းခံလွှာကို ပြင်ဆင်ပြီးဖြစ်သည်။",
    'invoice_setting' => 'ပြေစာ ဆက်တင်',
    'invoice_logo' => 'ပြေစာ အမှတ်အသား',
    'auto_generate_receipt' => 'ပြေစာကို အလိုအလျောက်ထုတ်ပေးသည်။',
    'auto_email_receive_to_customer' => 'ဖောက်သည်ထံမှ အလိုအလျောက် အီးမေးလ်လက်ခံခြင်း။',
    'invoice_start_from' => 'ပြေစာ(form)',
    'sales_invoice_settings' => 'အရောင်းပြေစာ ဆက်တင်များ',
    'tenant_is_inactive' => 'အငှားမရှိသေးပါ',
    'invite_tenant_response' => 'အငှားကိုလုပ်ဆောင်ချက်အောင်မြင်ပါသည်',
    'go_to_destination' => '{destination} သို့ သွားပါ',
    'tenantInvitation' => 'အငှားဖိတ်ခေါ်ခြင်း',
    'contents' => 'မာတိကာ',
    'tenant_activated_successfully' => '{name} အောင်မြင်စွာ ထည့်သွင်းပြီးပါပြီ။',
    'tenant_already_activated' => '{name} ပါဝင်ပြီး ဖြစ်နေပါပြီ။',
    'tenant_activation_login_response' => 'လော့ဂ်အင်စာမျက်နှာသို့ ဝင်ရောက်ကြည့်ရှုခြင်းဖြင့် သို့မဟုတ် အောက်ပါလင့်ခ်ကို နှိပ်ခြင်းဖြင့် သင်သည်ယခု {name} သို့ ဝင်ရောက်နိုင်ပါပြီ။',
    'congratulation' => 'ဂုဏ်ယူပါတယ် {name} ။',
    'tenant_activation' => 'အငှားပါဝင်ခြင်း',
    'user_associated_with_app_should_not_be_invited_in_tenant' => 'အက်ပ်နှင့် ဆက်စပ်အသုံးပြုသူသည် အငှားမဖြစ်သင့်ပါ။',
    'login' => 'အကောင့်ဝင်ပါ',
    'log_in_as' => 'အဖြစ်အကောင့်ဝင်ပါ',
    'alert' => 'သတိပေးချက်',
    'confirm_your_account' => 'သင့်အကောင့်ကို အတည်ပြုပါ။',
    'add_admin_role_can_not_switch_to_other' => "အက်ပ်စီမံခန့်ခွဲသူအခန်းကဏ္ဍကို အခြားသို့ ပြောင်းလဲ၍မရပါ။",
    'choose_a_role' => 'အခန်းကဏ္ဍတစ်ခုကို ရွေးချယ်ပါ။',

    // Add and all labels
    'field_label' => '{subject} {key}',
    'all_feature_name' => '{name} အားလုံး',
    'add_feature_name' => '{name} ကိုထည့်ပါ။',
    'edit_feature_name' => '{name} ကို တည်းဖြတ်ပါ',
    'copy_feature_name' => '{name} ကို ကူးယူပါ',
    'field_title' => '{subject} {infix} {title}',
    'place_holder' => '{subject} {type} ကို ထည့်ပါ',

    //Settings
    'app_name' => 'အက်ပ်အမည်',
    'show' => 'ပြပါ။',
    'hide' => 'ဝှက်ပါ။',

    // Status
    'status_active' => 'ပါဝင်သည်။',
    'status_deactive' => 'အလုပ်မလုပ်ပါ။',
    'status_pending' => 'ဆိုင်းငံ့ထားသည်။',
    'status_deleted' => 'ဖျက်လိုက်ပါသည်။',
    'status_processing' => 'လုပ်ဆောင်နေသည်',
    'status_sent' => 'ပို့လိုက်ပါသည်။',
    'status_draft' => 'မူကြမ်း',
    'status_regular' => 'ပုံမှန်',
    'status_auto' => 'အလိုအလျောက်',
    'status_dynamic' => 'အသက်ဝင်သည်(Dynamic)',
    'status_imported' => 'တင်သွင်းခဲ့သည်။',
    'status_black-listed' => 'နာမည်ပျက်စာရင်းသွင်းထားသည်။',
    'status_inactive' => 'အသုံးမပြုပါ။',
    'status_invited' => 'ဖိတ်ခေါ်ခဲ့သည်။',
    'status_open' => 'ဖွင့်သည်',
    'status_close' => 'ပိတ်သည်',
    'status_delivered' => 'ပေးပို့ခဲ့သည်',
    'status_declined' => 'ငြင်းဆိုခဲ့သည်',
    'status_hold' => 'ထိန်းချုပ်သည်',
    'status_done' => 'ပြီးဆုံးသည်',
    'status_cancel' => 'ပယ်ဖျက်သည်။',
    'status_return' => 'အကြောင်းပြန်သည်။',
    'status_partial_return' => 'တစ်စိတ်တစ်ပိုင်းအကြောင်းပြန်သည်။',

    // Permissions
    'manage_dashboard' => 'အက်ပ်ဒက်ရှ်ဘုတ်(app dashboard)ကို စီမံခန့်ခွဲနိုင်ပါသည်။',
    'view_users' => 'အသုံးပြုသူစာရင်းကိုကြည့်ရှုနိုင်ပါသည်။',
    'create_users' => 'အသုံးပြုသူကိုဖန်တီးနိုင်ပါသည်။',
    'update_users' => 'အသုံးပြုသူကို ပြုပြင်လုပ်နိုင်ပါသည်။',
    'delete_users' => 'အသုံးပြုသူကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'view_brands' => 'အမှတ်တံဆိပ်စာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_brands' => 'အမှတ်တံဆိပ်ကို ဖန်တီးနိုင်သည်။',
    'update_brands' => 'အမှတ်တံဆိပ်ကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_brands' => 'အမှတ်တံဆိပ်ကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'user_list_brands' => 'အမှတ်တံဆိပ်တစ်ခု၏အသုံးပြုသူများကိုကြည့်ရှုနိုင်သည်။',
    'attach_users_brands' => 'အသုံးပြုသူကို အမှတ်တံဆိပ်နဲ့ တွဲနိုင်ပါတယ်။',
    'detach_users_brands' => 'အသုံးပြုသူကို အမှတ်တံဆိပ်တစ်ခုမှ ခွဲထုတ်နိုင်သည်။',
    'brand_list_users' => 'အသုံးပြုသူ၏ အမှတ်တံဆိပ်များကို ကြည့်ရှုနိုင်သည်။',
    'manage_brand_dashboard' => 'အမှတ်တံဆိပ် ဒက်ရှ်ဘုတ် (dashboard)ကို ကြည့်ရှုနိုင်သည်။',
    'update_brand_privacy_settings' => 'အမှတ်တံဆိပ်၏ ကိုယ်ရေးကိုယ်တာများကို  အက်ပ်(app)မှ ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'view_brand_privacy_settings' => 'အမှတ်တံဆိပ်၏ ကိုယ်ရေးကိုယ်တာများကို အက်ပ်(app)မှကြည့်ရှုနိုင်သည်။',
    'view_roles' => 'အခန်းကဏ္ဍစာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_roles' => 'အခန်းကဏ္ဍကို ဖန်တီးနိုင်သည်။',
    'update_roles' => 'အခန်းကဏ္ဍကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_roles' => 'အခန်းကဏ္ဍကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'view_settings' => 'ဆက်တင်စာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'update_settings' => 'ဆက်တင်ကို  ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'view_permission' => 'ခွင့်ပြုချက်စာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'view_custom_fields' => 'စိတ်ကြိုက်အကွက်စာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_custom_fields' => 'စိတ်ကြိုက်အကွက် ဖန်တီးနိုင်သည်။',
    'update_custom_fields' => 'စိတ်ကြိုက်အကွက်ကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_custom_fields' => 'စိတ်ကြိုက်အကွက်ကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'attach_roles_users' => 'အသုံးပြုသူများထံသို့ အခန်းကဏ္ဍများ ပူးတွဲလုပ်ဆောင်နိုင်သည်။',
    'detach_roles_users' => 'အသုံးပြုသူများထံမှ အခန်းကဏ္ဍများကို ခွဲခြားနိုင်သည်။',
    'attach_permissions_roles' => 'အခန်းကဏ္ဍတွင် ခွင့်ပြုချက်များကို ပူးတွဲတင်ပြနိုင်သည်။',
    'detach_permissions_roles' => 'ခွင့်ပြုချက်များကို အခန်းကဏ္ဍမှ ဖယ်ရှားနိုင်သည်။',
    'change_settings_users' => 'ကိုယ်ပိုင်ဆက်တင်များကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'settings_list_users' => 'ဆက်တင်စာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'change_password_users' => 'အသုံးပြုသူစကားဝှက်ကို ပြောင်းလဲနိုင်ပါသည်။',
    'change_profile_picture_users' => 'ပရိုဖိုင်ပုံပြောင်းနိုင်သည်။',
    'update_delivery_settings' => 'အီးမေးလ်ဆက်တင်များကို ပြောင်းလဲနိုင်ပါသည်။',
    'update_corn_job_settings' => 'corn job ဆက်တင်များကို ပြောင်းလဲနိုင်ပါသည်။',
    'view_corn_job_settings' => 'corn job ဆက်တင်များကို ကြည့်ရှုနိုင်ပါသည်။',
    'view_delivery_settings' => 'အီးမေလ်းဆက်တင်များကို ကြည့်ရှုနိုင်ပါသည်။',
    'view_brand_delivery_settings' => 'ကုန်အမှတ်တံဆိပ်အီးမေးလ်ဆက်တင်များကိုကြည့်ရှုနိုင်သည်။',
    'view_notification_settings' => 'အကြောင်းကြားချက် ဆက်တင်များကို ကြည့်ရှုနိုင်သည်။',
    'update_notification_settings' => 'အကြောင်းကြားချက် ဆက်တင်များကို ပြောင်းလဲနိုင်ပါသည်။',
    'create_brand_groups' => 'အမှတ်တံဆိပ်အဖွဲ့ ဖန်တီးနိုင်သည်။',
    'view_brand_groups' => 'အမှတ်တံဆိပ်အဖွဲ့ကို ကြည့်ရှုနိုင်ပါသည်။',
    'update_brand_groups' => 'အမှတ်တံဆိပ်အဖွဲ့ကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_brand_groups' => 'ကုန်အမှတ်တံဆိပ်အဖွဲ့ကို ဖျက်သိမ်းနိုင်သည်',
    'attach_brand_brand_groups' => 'အမှတ်တံဆိပ်အုပ်စုသို့ တံဆိပ်ကပ်နိုင်သည်။',
    'detach_brand_brand_groups' => 'အမှတ်တံဆိပ်ကို အမှတ်တံဆိပ်အုပ်စုမှ ခွဲထုတ်နိုင်သည်။',
    'view_brands_brand_groups' => 'အမှတ်တံဆိပ်အုပ်စုတစ်ခု၏ အမှတ်တံဆိပ်များကို ကြည့်ရှုနိုင်သည်။',
    'view_notification_templates' => 'အသိပေးချက်ပုံစံများကို ကြည့်ရှုနိုင်သည်။',
    'create_notification_templates' => 'အသိပေးချက်ပုံစံများကို ဖန်တီးနိုင်သည်။',
    'update_notification_templates' => 'အသိပေးချက်ပုံစံများကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_notification_templates' => 'အသိပေးချက်ပုံစံများကို ဖျက်သိမ်းနိုင်သည်။',
    'attach_templates_notification_events' => 'အကြောင်းကြားချက်ဖြစ်ရပ်တွင် နမူနာပုံစံများကို ပူးတွဲနိုင်သည်။',
    'detach_templates_notification_events' => 'ပုံစံများကို အသိပေးချက်ဖြစ်ရပ်သို့ ဖယ်ထုတ်နိုင်သည်။',
    'view_activity_logs' => 'လှုပ်ရှားမှုမှတ်တမ်းကို ကြည့်ရှုနိုင်သည်။',
    'view_templates' => 'နမူနာပုံစံများကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_templates' => 'နမူနာပုံစံများကိုဖန်တီးနိုင်သည်။',
    'update_templates' => 'နမူနာပုံစံများကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_templates' => 'နမူနာပုံစံများကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'invite_user' => 'အသုံးပြုသူကို ဖိတ်ကြားနိုင်သည်။',
    'view_tenant_groups' => 'အငှားအဖွဲ့များကို  ကြည့်နိုင်ပါသည်။',
    'create_tenant_groups' => 'အငှားအဖွဲ့များကို ဖန်တီးနိုင်ပါသည်။',
    'update_tenant_groups' => 'အငှားအဖွဲ့များကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_tenant_groups' => 'အငှားအဖွဲ့များကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'view_tenants' => 'အငှားများကို ကြည့်နိုင်ပါသည်။',
    'create_tenants' => 'အငှားများကို ဖန်တီးနိုင်ပါသည်။',
    'update_tenants' => 'အငှားများကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_tenants' => 'အငှားများကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'cancel_tenant_invitation' => 'အငှားဖိတ်ခေါ်ခြင်းကို ပယ်ဖျက်နိုင်ပါသည်။',
    'update_tenant_status' => 'အငှားအခြေအနေ(status)ကို ပြောင်းလဲ(update)နိုင်ပါသည်',
    'cancel_user_invitation' => 'အသုံးပြုသူ ဖိတ်ခေါ်ခြင်းကို ပယ်ဖျက်နိုင်သည်။',

    'date_format' => 'ရက်စွဲပုံစံ',
    'time_format' => 'အချိန်ပုံစံ',
    'decimal_separator' => 'ဒဿမ ပိုင်းခြားခြင်း',
    'thousand_separator' => 'ထောင်ဂဏန်း ပိုင်းခြားခြင်း',
    'number_of_decimal' => 'ဒဿမ အရေအတွက်',
    'currency_position' => 'ငွေကြေးအခြေအနေ',
    'currency_code' => 'ငွေကြေးစီမံသတ်မှတ်ချက်',

    //Branch warehouse permission
    'view_branch_or_warehouses' => 'navbar မှ ဌာနခွဲ သို့မဟုတ် သိုလှောင်ရုံများကို ပြောင်းနိုင်သည်။',
    'choose_branch_or_warehouse' => 'ဌာနခွဲ သို့မဟုတ် ဂိုဒေါင်ကို ရွေးပါ။',
    'please_select_a_branch_or_a_warehouse' => 'ဘဏ်ခွဲတစ်ခု သို့မဟုတ် သိုလှောင်ရုံတစ်ခုကို ရွေးချယ်ပါ။',
    'no_branch_or_warehouse_is_found' => 'ဘဏ်ခွဲ သို့မဟုတ် သိုလှောင်ရုံ မတွေ့ပါ။',
    'branch_or_warehouse_is_inactive' => 'ဌာနခွဲ သို့မဟုတ် ဂိုဒေါင်သည် အလုပ်မလုပ်ပါ။',

    //Lot Permission
    'lot_manage' => 'ကုန်ပစ္စည်းအစုအဖွဲ့ ကိုစီမံခန့်ခွဲနိုင်ပါသည်။',
    'view_lot' => 'အရေအတွက်စာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_lot' => 'များစွာဖန်တီးနိုင်ပါသည်။',
    'lot_add' => 'များစွာထည့်ထားသည့်ပုံစံကို ကြည့်ရှုနိုင်ပါသည်။',
    'update_lot' => 'များစွာ ပြောင်းလဲ(update)လုပ်နိုင်ပါသည်။',

    //Stock Permission
    'view_stock' => 'စတော့များ၏စာရင်းကိုကြည့်ရှုနိုင်ပါသည်။',

    //Stock adjustment permission
    'view_stock_adjustments' => 'စတော့ချိန်ညှိမှုစာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_stock_adjustments' => 'စတော့ရှယ်ယာ ပြုပြင်ပြောင်းလဲမှုများကို ဖန်တီးနိုင်သည်။',
    'update_stock_adjustments' => 'စတော့ရှယ်ယာချိန်ညှိမှုများကို အပ်ဒိတ်လုပ်နိုင်ပါသည်။',
    'delete_stock_adjustments' => 'စတော့ချိန်ညှိမှုများကို ဖျက်နိုင်သည်။',

    //Product permission
    'products_manage' => 'ထုတ်ကုန်ကိုစီမံခန့်ခွဲနိုင်သည်။',
    'view_products' => 'ကုန်ပစ္စည်းစာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_products' => 'ထုတ်ကုန်တစ်ခုဖန်တီးနိုင်သည်။',
    'update_products' => 'ထုတ်ကုန်ကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_products' => 'ထုတ်ကုန်ကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'import_products' => 'ကုန်ပစ္စည်းတင်သွင်းနိုင်ပါသည်။',
    'change_status_products' => 'ထုတ်ကုန်အခြေအနေကို ပြောင်းလဲနိုင်သည်။',

    //Group permission
    'view_groups' => 'အဖွဲ့စာရင်းကို ကြည့်ရှုနိုင်သည်။',
    'create_groups' => 'အဖွဲ့တစ်ခုကို ဖန်တီးနိုင်ပါသည်။',
    'update_groups' => 'အဖွဲ့တစ်ခုကို  ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'delete_groups' => 'အဖွဲ့တစ်ခုကို ဖျက်သိမ်းနိုင်ပါသည်။',

    //generate and print barcode
    'generate_barcode_inventory' => 'ဘားကုဒ်(barcode)ကို ထုတ်လုပ်ပြီး ပရင့်ထုတ်နိုင်သည်။',

    //generate and print qrcode
    //'generate_qrcode' => 'Can generate and print QR code',

    //Internal transfer Permission
    'view_internal_transfers' => 'အတွင်းပိုင်းလွှဲပြောင်းမှုစာရင်းကိုကြည့်ရှုနိုင်သည်။',
    'create_internal_transfers' => 'အတွင်းအပြောင်းအရွှေ့တစ်ခုကို ဖန်တီးနိုင်သည်။',
    'delete_internal_transfers' => 'အတွင်းပိုင်းလွှဲပြောင်းမှုကို ဖျက်နိုင်သည်။',
    'update_internal_transfers' => 'အတွင်းပိုင်းလွှဲပြောင်းမှုကို ပြောင်းလဲ(update)နိုင်ပါသည်။',

    //Category permission
    'categories_manage' => 'အမျိုးအစားများကို စီမံခန့်ခွဲနိုင်သည်။',
    'view_categories' => 'အမျိုးအစားများကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_categories' => 'အမျိုးအစားများကို ဖန်တီးနိုင်ပါသည်။',
    'delete_categories' => 'အမျိုးအစားများကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'update_categories' => 'အမျိုးအစားများကို ပြောင်းလဲ(update)နိုင်ပါသည်။',
    'change_category_status' => 'အမျိုးအစား အခြေအနေများကို ပြောင်းလဲနိုင်သည်။',

    //sub category permission
    'view_sub_categories' => 'အမျိုးအစားခွဲများကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_sub_categories' => 'အမျိုးအစားခွဲတစ်ခုကို ဖန်တီးနိုင်သည်။',
    'update_sub_categories' => 'အမျိုးအစားခွဲများကို ပြောင်းလဲ(update)လုပ်နိုင်ပါသည်။',
    'change_status_subcategory' => 'အမျိုးအစားခွဲအခြေအနေကို ပြောင်းလဲနိုင်သည်။',
    'delete_sub_categories' => 'အမျိုးအစားခွဲတစ်ခုကို ဖျက်နိုင်သည်။',

    //Units permission
    'change_unit_status' => 'သတ်မှတ်ထားသည့် စံနှုန်းကို ပြောင်းလဲနိုင်သည်။',

    //Attribute permission
    'view_attributes' => 'စာရင်းအချက်အလက်များကို ကြည့်နိုင်ပါသည်။',
    'create_attributes' => 'အချက်အလက်များကို ဖန်တီးနိုင်ပါသည်။',
    'update_attributes' => 'အချက်အလက်များကို ပြောင်းလဲနိုင်ပါသည်။',
    'delete_attributes' => 'အချက်အလက်များကို ဖျက်သိမ်းနိုင်ပါသည်။',
    'import_attributes' => 'အချက်အလက်များကို တင်သွင်းနိုင်ပါသည်။',

    //Dashboard permission
    'dashboard_tenant' => 'ဒက်ရှ်ဘုတ်စာမျက်နှာကို ကြည့်ရှုနိုင်ပါသည်။',

    //Expenses permission
    'view_expenses' => 'ကုန်ကျစရိတ်စာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_expenses' => 'ကုန်ကျစရိတ်ကို ဖန်တီးနိုင်ပါတယ်။',
    'update_expenses' => 'ကုန်ကျစရိတ်ကို ပြောင်းလဲနိုင်ပါတယ်။',
    'delete_expenses' => 'ကုန်ကျစရိတ်ကို ဖျက်သိမ်းနိုင်ပါသည်။',

    //Expense areas permission
    'expense_areas' => 'အသုံးစရိတ်ပမာဏများ',
    'view_expense_areas' => 'အသုံးစရိတ်ပမာဏစာရင်းများကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_expense_areas' => 'အသုံးစရိတ်ပမာဏစာရင်းများကို ဖန်တီးနိုင်ပါသည်။',
    'update_expense_areas' => 'အသုံးစရိတ်ပမာဏစာရင်းများကို အက်ပ်ဒိတ် လုပ်နိုင်ပါသည်။',
    'delete_expense_areas' => 'အသုံးစရိတ်ပမာဏစာရင်းများကို ဖျက်သိမ်းနိုင်ပါသည်။',

    //supplier permission
    'view_suppliers' => 'ပေးသွင်းသူများစာရင်းကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_suppliers' => 'ပေးသွင်းသူကို ဖန်တီးနိုင်သည်။',
    'update_suppliers' => 'ပေးသွင်းသူအား အပ်ဒိတ်လုပ်နိုင်သည်။',
    'delete_suppliers' => 'ပေးသွင်းသူကို ဖျက်နိုင်သည်။',
    'please_enter_the_supplier_name' => 'ကျေးဇူးပြု၍ ပေးသွင်းသူအမည်ကို ထည့်သွင်းပါ။',
    'please_enter_the_supplier_no' => 'ကျေးဇူးပြု၍ ပေးသွင်းသူနံပါတ်ကို ထည့်ပါ။',

    //Customer permission
    'details_customer' => 'ဖောက်သည်အသေးစိတ်အချက်အလက်များကိုကြည့်ရှုနိုင်သည်။',
    'info_customer' => 'ဖောက်သည်အချက်အလက်ကိုကြည့်ရှုနိုင်သည်။',
    'not_allow_to_modify' => 'သင့်အားပြင်ဆင်ခွင့်မပြုထားပါ။ ကြည့်ရှုရုံသာ',
    //Sales view permission
    'view_sales' => 'အရောင်းပိုင်းကိုကြည့်ပါ။',

//    Report permission
    'counter_is_in_use' => 'ကောင်တာအသုံးပြုနေပါသည်။',
    'view_sales_report' => 'တင်ပို့ရောင်းချမှုအစီရင်ခံစာကို ကြည့်ရှုနိုင်သည်။',
    'view_cash_counter_report' => 'ငွေသားကောင်တာအစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'view_sales_return_report' => 'အရောင်းအ၀ယ်အစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'view_top_selling_product_report' => 'အရောင်းရဆုံးထုတ်ကုန်အစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'view_lot_report' => 'အစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'view_stock_report' => 'စတော့ရှယ်ယာအစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'view_branch_warehouse_report' => 'ဌာနခွဲ/ဂိုဒေါင်အစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'view_profit_loss_report' => 'အမြတ်အစွန်း အစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'view_user_report' => 'အသုံးပြုသူအစီရင်ခံစာကိုကြည့်ရှုနိုင်သည်။',
    'view_expense_report' => 'ကုန်ကျစရိတ်အစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'view_supplier_report' => 'ပေးသွင်းသူအစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'view_customer_report' => 'ဖောက်သည်အစီရင်ခံစာကို ကြည့်ရှုပြီး တင်ပို့နိုင်သည်။',
    'create_return_order' => 'မှာယူမှုကို ဖန်တီး/သိမ်းဆည်းနိုင်သည်။',
    'view_order_return' => 'အော်ဒါပြန်ပို့သည်ကို ကြည့်နိုင်ပါသည်။',
    'view_sale_return' => 'အရောင်းပြန်တမ်းကိုကြည့်နိုင်သည်။',

    //
    'list_invoice' => 'ပြေစာစာရင်းများကို ကြည့်ရှုနိုင်ပါသည်။',

    'sales_return' => 'အရောင်းပြန်တမ်း',
    'switch_branch' => 'ဘဏ်ခွဲကိုပြောင်းပါ။h',

    'stock_alert'=> 'စတော့ သတိပေးချက်',

    // Language
    'en' => 'အင်္ဂလိပ်စာ',

    // Date Format
    'dd-mm-yyyy' => 'DD-MM-YYYY',

    // Time Format
    'h' => '၁၂နာရီ',
    'H' => '၂၄နာရီ',

    // Decimal and Thousand Separator
    '.' => 'အစက်(.)',
    ',' => 'COMMA(,)',

    // Currency Positions
    'prefix_only' => '$1,100.00',
    'prefix_with_space' => '$ 1,100.00',
    'suffix_only' => '1,100.00$',
    'suffix_with_space' => '1,100.00 $',

    // Validation
    "is_required" => "လိုအပ်ပါသည်",
    "and" => "နှင့်",
    "this_field_is_required" => "ဤစာကွက်လပ်မှာဖြည့်ရန်လိုအပ်ပါသည်",
    "this_field_is_invalid" => "ဤအကွက်သည် မမှန်ကန်ပါ။",
    "this_field_is_not_alphanumeric" => "ဤအကွက်သည် အက္ခရာဂဏန်းမဟုတ်ပါ။",
    "passwords_are_not_matched" => "စကားဝှက်များနှင့် မကိုက်ညီပါ။",
    "please_enter_a_strong_password" => "ကျေးဇူးပြု၍ လုံခြုံသော စကားဝှက်တစ်ခု ထည့်ပါ။",
    "are_not_match" => "မကိုက်ညီပါ။",
    "can_not_before" => "မတိုင်ခင်လုပ်လို့မရသေးပါ။",
    "is_invalid" => "မမှန်ပါ။",
    "minimum_length_is" => "အနည်းဆုံးအရှည်သည်",
    "maximum_length_is" => "အများဆုံးအရှည်သည်",
    "maximum_number_is" => "အများဆုံးနံပါတ်သည်",
    "minimum_number_is" => "အနည်းဆုံးနံပါတ်သည်",
    "is_not_alphanumeric" => "အက္ခရာဂဏန်းမဟုတ်ပါ။",
    "not_found" => "မတွေ့ပါ",
    'app_settings' => 'အက်ပ်ဆက်တင်များ',
    'save' => 'သိမ်းဆည်းပါ။',
    ' ' => 'နေရာလပ်(space)',
    'provider' => 'ပံ့ပိုးပေးသူ',
    'mandrill' => 'Mandrill',
    'secret' => 'လျှို့ဝှက်ချက်',
    'smtp' => 'SMTP',
    'mailgun' => 'Mailgun',
    'domain_name' => 'နယ်ပယ်နာမည်',
    'api_key' => 'API ကီး',
    'from' => 'ထံမှ',
    'host' => 'ပိုင်ရှင်(အစီအစဉ်မှုး)',
    'port' => 'ဆိပ်ကမ်း',
    'encryption' => 'ကုဒ်ဝှက်ခြင်း',
    'amazon_ses' => 'အမေဇုန် SES',
    'api_region' => 'API ဒေသ',
    'access_key_id' => 'ဝင်ခွင့်ကီး',
    'secret_access_key' => 'လျှို့ဝှက်ဝင်ရောက်ခွင့်ကီး',
    'postmark' => 'စာတိုက်',
    'token' => 'Token',
    'sparkpost' => 'မီးပွားတိုင်',
    'sendmail' => 'စာပို့ပါ။',
    'path' => 'လမ်းကြောင်း',
    'tenant_logo' => 'အငှားအမှတ်တံဆိပ်',
    'logo' => 'အမှတ်တံဆိပ်',
    'personal_info' => 'ကိုယ်ရေးကိုယ်တာအချက်အလက်',
    'personal_information' => 'ကိုယ်ပိုင်သတင်းအချက်အလက်များ',
    'first_name' => 'အစနာမည်',
    'last_name' => 'နောက်ဆုံးနာမည်',
    'gender' => 'ကျား/မ',
    'date_of_birth' => 'မွေးနေ့',
    'contact' => 'ဆက်သွယ်ရန်',
    'address' => 'လိပ်စာ',
    'rows' => 'အတန်းလိုက်',
    'sheet' => 'စာရွက်',
    'not_added_yet' => 'မထည့်ရသေးပါ။',
    'male' => 'ကျား',
    'female' => 'မ',
    'password_requirements_message' => 'စကားဝှက်တွင် စာလုံးအကြီးတစ်ခု၊ စာလုံးအသေးတစ်ခု၊ အထူးစာလုံးတစ်လုံးနှင့် နံပါတ်များ ပါဝင်သင့်သည်။ အနည်းဆုံး စာလုံး 8 လုံးရှိရပါမည်။',
    'new' => 'အသစ်',
    'old' => 'အဟောင်း',
    'confirm' => 'အတည်ပြုသည်',
    'old_password' => 'စကားဝှက်ဟောင်း',
    'notification_setting' => 'အကြောင်းကြားချက် ဆက်တင်',
    'account_is_not_activated_warning_for_new_tenant_invitation' => 'အငှားအသစ် ဖိတ်ကြားချက်အတွက် တောင်းဆိုထားသော အသုံးပြုသူကို အသုံးပြုခွင့်မပေးပါ။',
    'this_resource_already_referenced_message' => 'အမှားတစ်ခုခုဖြစ်သွားပါသည်။ လုပ်ဆောင်ချက်ကိုလုပ်ဆောင်၍မရပါ။',

    // Login
    "hi" => "မင်္ဂလာပါ",
    "copyright" => "မူပိုင်ခွင့်",
    "login_to_your_dashboard" => "သင်၏ ဒက်ရှ်ဘုတ်သို့ ဝင်ရောက်ပါ။",
    "your" => "သင်၏",
    "forget" => "{subject} မေ့သွားသည်။",
    "reset_password" => "စကားဝှက်ကိုပြန်လည်သတ်မှတ်ပါ။",
    "back_to" => "{destination}သို့ ပြန်သွားရန်",
    "request" => "တောင်းဆိုချက်",
    "change" => "ပြောင်းလဲသည်",
    "password_must_contains_things" => "စကားဝှက်တွင် နံပါတ်၊ စာလုံးသေး၊ စာလုံးကြီးနှင့် အထူးအက္ခရာများ ပါဝင်ရပါမည်။",

    'remember_me' => 'ကျွန်ုပ်ကိုမှတ်ထားပါ။',

    'starts_at' => 'တွင်စတင်သည်',
    'ends_at' => 'တွင်အဆုံးသတ်သည်။',
    'is_default' => 'ပုံသေဖြစ်သည်။',
    'start_time' => 'စတင်ချိန်',

    'sun' => 'တနင်္ဂနွေ',
    'mon' => 'တနင်္လာနေ့',
    'tue' => 'အင်္ဂါ',
    'wed' => 'ဗုဒ္ဓဟူးနေ့',
    'thu' => 'ကြာသပတေးနေ့',
    'fri' => 'သောကြာနေ့',
    'sat' => 'စနေနေ့',


    'class' => 'အမျိုးအစား',
    'purple' => 'ခရမ်းရောင်',
    'success' => 'အောင်မြင်မှု',
    'info' => 'အချက်အလက်',
    'warning' => 'သတိပေးချက်',
    'primary' => 'မူလ',
    'danger' => 'အန္တရာယ်',
    'okay' => 'okay',

    // Btn
    "load_more" => "ပိုတင်ပါ။",
    "apply" => "လျှောက်ထားသည်။",
    "clear" => "ရှင်းလင်းသည်။",
    "close" => "ပိတ်သည်",
    "open" => "ဖွင့်သည်။",
    "yes" => "Yes",
    "no" => "No",
    "more" => "နောက်ထပ်",
    "actions" => "လုပ်ဆောင်ချက်များ",
    "action" => "လုပ်ဆောင်ချက်",

    // Multi select component
    'add' => 'ထည့်သည်။',
    'edit' => 'ပြင်ဆင်သည်။',
    'delete' => 'ဖျက်သိမ်းသည်။',
    'de_activate' => 'ရပ်ဆိုင်းသည်/ပိတ်သိမ်းသည်။',
    'activate' => 'အသုံးပြုခွင့်ပေးသည်',
    'manage' => 'စီမံသည်။',
    'attach_users_to_roles' => 'အသုံးပြုသူများကို အခန်းကဏ္ဍသို့ ချိတ်ဆက်ပါ။',

    // Datatable
    "items_showing_per_page" => 'စာမျက်နှာတစ်ခုစီတွင် ပြထားသည့်အရာများ',
    "items_selected" => "ရွေးချယ်ထားသော ပစ္စည်းများ",
    "select_all" => "အားလုံးကိုရွေးချယ်သည်။",
    "clear_selection" => "ရွေးချယ်မှုကို ရှင်းလင်းသည်။",
    "showing" => "ပြခြင်း",
    "to" => "သို့",
    "items" => "ပစ္စည်းများ",
    "of" => "၏",
    "go_to_page" => "စာမျက်နှာသို့သွားပါ",
    "loading" => "လုပ်ဆောင်နေသည်",
    "next_five_pages" => "နောက်စာမျက်နှာများ ၅ခု သို့",
    "previous_five_pages" => "ယခင် စာမျက်နှာများ ၅ခု",
    "click_to_highlights" => "မီးမောင်းထိုးပြရန် နှိပ်ပါ။",

    // Filters
    "filters" => "စစ်ထုတ်မှုများ",
    "clear_filters" => "စစ်ထုတ်မှုများကို ရှင်းလင်းပါ။",
    "minimum_rate" => "အနည်းဆုံးနှုန်း",
    "maximum_rate" => "အများဆုံးနှုန်း",
    "want_to_manage_datatable" => "ဒေတာဇယားကို စီမံခန့်ခွဲလိုပါသလား။",
    "please_drag_and_drop_your_column_to_reorder_your_table_and_enable_see_option_as_you_want" => "ကျေးဇူးပြု၍ သင့်ဇယားကို ပြန်စီရန်နှင့် သင်အလိုရှိသည့်အတိုင်း see option ကိုဖွင့်ရန် သင့်ကော်လံကို ဆွဲယူပြီး ချပေးပါ။",
    "manage_columns" => "Columnsများကို စီမံပါ။",
    "search" => "ရှာဖွေသည်။",
    "today" => "ဒီနေ့",
    "select_an_option" => "ရွေးချယ်မှုတစ်ခုကို ရွေးချယ်ပါ။",
    "clear_all_filters" => "စစ်ထုတ်မှုများအားလုံးကို ရှင်းလင်းပါ။",
    "sort_by" => "အစဉ်လိုက်စီသည်။",
    "saved_filter" => "စစ်ထုတ်မှုကို သိမ်းဆည်းထားသည်။",
    "filter_name" => "အမည်ကို စစ်ထုတ်ပါ။",
    "save_current_filter_state" => "လက်ရှိ စစ်ထုတ်မှုအခြေအနေကို သိမ်းဆည်းပါ။",
    "select_form_previous_state" => "ယခင်စစ်ထုတ်မှုအခြေအနေမှ ရွေးချယ်ပါ။",
    "at_least_one_filter_should_have_selected" => "အနည်းဆုံး စစ်ထုတ်မှုတစ်ခု ရွေးထားသင့်သည်။",
    "filter_saved_instruction" => "သင်၏ယခင်သိမ်းဆည်းထားသည့် စစ်ထုတ်မှုမှ သင်ရွေးချယ်နိုင်သည်။ သို့မဟုတ် အနာဂတ်အတွက် လက်ရှိစစ်ထုတ်မှုအခြေအနေကို သိမ်းဆည်းနိုင်သည်။",

    // Modal
    "are_you_sure" => "သေချာပါသည်",
    "this_content_will_be_deleted_permanently" => "ဤအကြောင်းအရာကို အပြီးတိုင် ဖျက်လိုက်ပါမည်။",

    // Empty data
    "nothing_to_show_here" => "ဤနေရာတွင် ပြစရာမရှိပါ။",
    "thank_you" => "ကျေးဇူးတင်ပါသည်။",
    "go_back_to_your_page" => "သင့်စာမျက်နှာသို့ ပြန်သွားပါ။",
    "something_went_wrong" => "တစ်ခုခုမှားသွားခဲ့သည်။",
    "empty_data_block_dummy_message" => "အကြောင်းအရာကို ဤနေရာတွင်ကြည့်ရန် ကျေးဇူးပြု၍ အကြောင်းအရာအသစ်တစ်ခု ထည့်ပါ သို့မဟုတ် ဒေတာဇယားကို စီမံခန့်ခွဲပါ။",

    // File upload
    "change_image" => "ပုံပြောင်းပါ။",
    "choose_file" => "ဖိုင်ကိုရွေးပါ။",
    "drag_and_drop" => "ဆွဲချလိုက်ပါ။",
    "or" => "သို့မဟုတ်",
    "browse" => "ရှာဖွေကြည့်ရှုပါ(browse)",

    // No notification
    "no_notification_one" => "ပုံမှန်ခါတိုင်းလို လုပ်ရတာ ပျင်းတယ်၊ ဘီယာနဲ့ ပါတီပွဲ လုပ်လိုက်ကြရအောင်!",
    "no_notification_two" => "သင်ဗိုက်ဆာနေဘီလား? အစားကောင်းကောင်းစားပြီးပျော်ရွှင်စွာ အလုပ်ပြန်လုပ်လိုက်ပါ!",
    "no_notification_three" => "ရော့ခ်နှင့် သရုပ်ဆောင်ချိန်။ သီချင်းကိုဖွင့်ပြီး သင့်အဖွဲ့နှင့် ပျော်ရွှင်လိုက်ပါ!",
    "all_notifications" => "အသိပေးချက်အားလုံး",

    // Tooltip titles
    "collapse_sidebar" => "ဘေးဘားကို သိမ်းပါ။",
    "floating_sidebar" => "floating sidebar",
    "full_sidebar" => "ဘေးဘောင်အပြည့်",
    "light_mood" => "အလင်း",
    "dark_mood" => "အမှောင်",
    "fullscreen" => "မျက်နှာပြင်အပြည့်",
    "exit_fullscreen" => "မျက်နှာပြင်အပြည့်မှ ထွက်ပါ။",

    // Labels
    "tenant" => "အငှား",
    "tenants" => "အငှားများ",
    "tenant_and_groups" => "အငှားနှင့် အဖွဲ့များ",
    "choose" => "{field} ကို ရွေးပါ",
    "email_address" => "အီးမေလ်းလိပ်စာ",
    "tenant_name" => "အငှားနာမည်",
    "choose_field" => "{field} ကိုရွေးပါ။",
    'select_field' => '{field} ကို ရွေးပါ',
    'user_invitation' => 'အသုံးပြုသူ ဖိတ်ကြားချက်',
    'all_branch' => 'ဆိုင်ခွဲအားလုံး',
    'all_branch_and_warehouses' => 'ဆိုင်ခွဲများနှင့် ဂိုဒေါင်များအားလုံး',

    // Tenants
    "visit_tenant" => "Visit Tenant",
    "short_name" => "နာမည်အတိုကောက်",
    "go" => "သွားသည်",
    "options" => "ရွေးချယ်စရာများ",
    "choose_a" => "{field} ကိုရွေးပါ",
    "context" => "စကားစပ်",
    "custom_fields" => "စိတ်ကြိုက်အကွက်များ",

    // Tenant Preview Card
    "invited_by" => "ဖိတ်ကြားထားသည်။",
    "go_to_dashboard" => "Dashboard သို့သွားပါ။",
    'user_invitation_canceled_successfully' => 'အသုံးပြုသူ ဖိတ်ကြားချက်ကို အောင်မြင်စွာ ပယ်ဖျက်လိုက်ပါပြီ။',
    "you_are_going_to_cancel_an_invitation" => "သင်သည် ဖိတ်ကြားချက်ကို ပယ်ဖျက်တော့မည်ဖြစ်သည်။",
    "edit_tenant" => "အိမ်ငှားကို တည်းဖြတ်ပါ။",
    "cancel_invitation" => "ဖိတ်ကြားချက်ကို ပယ်ဖျက်ပါ။",
    "please_add_a_new_entity_to_see_the_content_here" => "ဤအကြောင်းအရာကိုကြည့်ရန် အကြောင်းအရာအသစ်တစ်ခုကို ကျေးဇူးပြု၍ထည့်ပါ။",
    "deactivate" => "ပိတ်သိမ်းသည်/ရပ်ဆိုင်းသည်။",
    "you_are_going_to_activate_a_tenant" => "သင်သည် အငှားကို အသုံးပြုခွင့်ပေးလိုက်ပါတော့မည်။",
    "you_are_going_to_deactivate_a_tenant" => "သင်သည် အငှားကို အသုံးပြုခွင့်ပိတ်လိုက်ပါတော့မည်",
    "hands_up" => "လက်မြှောက်လိုက်ပါပြီ။",
    'setting' => 'ဆက်တင်များ',
    'time_zone' => 'အချိန်ကန့်သတ်ချက်',
    'currency_symbol' => 'ငွေကြေးသင်္ကေတ',
    'app_icon' => 'အက်ပ်အိုင်ကွန်',
    'app_logo' => 'အက်ပ် အမှတ်အသား',
    'groups' => 'အဖွဲ့များ',
    'created_date' => 'ဖန်တီးသည့်ရက်စွဲ',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'invited' => 'ဖိတ်ခေါ်ပါသည်။',
    'go_to' => 'သွားရန်',
    'title' => 'ခေါင်းစဉ်',

    // Contact
    'contacts' => 'အဆက်အသွယ်များ',
    'all_customers' => 'Customers များအားလုံး',
    'customers' => 'ဝယ်ယူသူ',
    'customer_group' => 'ဝယ်ယူသူအဖွဲ့',
    'customer_groups' => 'ဝယ်ယူသူအဖွဲ့များ',
    'all_suppliers' => 'ပင်ရင်း(supplier)',
    'suppliers' => 'Suppliers',
    'suppleir_groups' => 'Supplier Groups',
    'supplier_name' => 'Supplier name',
    'supplier_id' => 'Supplier ID',
    'supplier_details' => 'Supplier Details',
    'back_to_suppliers' => 'Back to supplier',
    'total_lot' => 'Total lot',
    'phone_number' => 'Phone number',
    'company' => 'Company',
    'tin' => 'Tin',
    'customer' => 'Customer',
    'customer_details' => 'Customer details',
    'group_name' => 'Group name',
    'tin_number' => 'Tin number',
    'view_customer_groups' => 'View customer groups',
    'create_customer_groups' => 'Create customer groups',
    'update_customer_groups' => 'Update customer groups',
    'delete_customer_groups' => 'Delete customer groups',
    'view_customers' => 'View customers',
    'create_customers' => 'Create customers',
    'update_customers' => 'Update customers',
    'delete_customers' => 'Delete customers',
    'export_lists' => 'Export Lists',
    'select_a_country' => 'Select a country',
    'country' => 'Country',

    // Cash register
    'register_info' => 'Counter Info',
    'cash_register' => 'Cash Counter',
    'cash_registers' => 'Cash Counters',
    'open_register' => 'Open Counter',

    // Invoice Template
    'invoice_view' => 'ပြေစာကြည့်သည်။',
    'invoice_template' => 'ပြေစာပုံစံ(template)',
    'invoice_templates' => 'ပြေစာပုံစံများ(templates)',
    'invoice_summary' => 'ပြေစာအကျဉ်းချုပ်',
    'invoice_number' => 'ပြေစာနံပါတ်',
    'sold_to' => 'ရောင်းရန်',
    'mark_as_default' => 'မူရင်းအဖြစ် မှတ်ထားပါ။',
    'sales_invoice' => 'အရောင်းပြေစာ',
    'return_invoice_view' => 'ပြေစာပြန်သည့်စာများကို ကြည့်သည်။',
    'return_order' => 'အမှာပစ္စည်း များကိုပြန်ပို့ရန်(return_order)',
    'return_date' => 'ရက်စွဲကိုပြန်ရန်(return date)',
    'billar' => 'ဘီလာ(Billar)',
    'view_invoice_templates' => 'ပြေစာပုံစံများ(templates) ကိုကြည့်သည်။',
    'create_invoice_templates' => 'ပြေစာပုံစံများ(templates) ကိုဖန်တီးသည်။',
    'update_invoice_templates' => 'ပြေစာပုံစံများ(templates) ကိုပြောင်းလဲ(update)သည်။',
    'delete_invoice_templates' => 'ပြေစာပုံစံများ(templates) ကိုဖျက်သ်မ်းသည်။',
    'default' => 'မူရင်း/ပုံသေ',
    'purchase_invoice' => 'ဝယ်ယူမှုပြေစာ',
    'select_type' => 'အမျိုးအစားကိုရွေးချယ်ပါ။',
    'this_template_will_be_applicable_automatically_for_invoice' => 'ပြေစာအတွက် ဤပုံစံ(template)ကို အလိုအလျောက် အသုံးပြုပါမည်။',

    // Employee
    'employees' => 'ဝန်ထမ်းများ',
    'add_department' => 'ဌာနထည့်ရန်"',
    'department_name' => 'ဌာနနာမည်',
    'move_employee' => 'ဝန်ထမ်းပြောင်းရွှေ့ခြင်း',
    'select_employee' => 'ဝန်ထမ်းရွေးချယ်ရန်',
    'choose_all_employee' => 'ဝန်ထမ်းများအားလုံးရွေးချယ်ရန်',
    'manager' => 'စီမံခန့်ခွဲသူ',
    'no_employees_found' => 'ဝန်ထမ်းများမတွေ့ပါ။',
    'no_employees_warning' => 'ဤဌာနတွင် ဝန်ထမ်းများမတွေ့ပါ။',
    'available_departments' => 'ရရှိနိုင်သောဌာနများ',
    'do_you_want_to_move_employee' => 'ဝန်ထမ်းများရွှေ့ပြောင်းချင်ပါသလား?',
    'you_are_going_to_deactivate_a_department' => 'ဌာနတစ်ခုကို ပိတ်ပစ်မည်',
    'you_are_going_to_activate_a_department' => 'ဌာနတစ်ခုကို အသုံးပြုခွင့်ပေးမည်',

    // Settings
    'company_info' => 'ကုမ္ပဏီအချက်အလက်',
    'company_name' => 'ကုမ္ပဏီနာမည်',
    'type_your_company_name' => 'ကုမ္ပဏီနာမည်ကိုရိုက်ထည့်ပါ',
    'company_logo' => 'ကုမ္ပဏီ အမှတ်တံဆိပ်',
    'change_logo' => 'အမှတ်တံဆိပ်ကို ပြောင်းရန်',
    'company_icon' => 'ကုမ္ပဏီအိုင်ကွန်',
    'company_banner' => 'Company banner',
    'change_icon' => 'အိုင်ကွန်(icon)ကိုပြောင်းရန်',
    'change_banner' => ' bannerပြောင်းရန်',
    'recommended_company_logo_size' => '(အကြံပြုထားသောအရွယ်အစား: ၂၁၀ x ၅၀ px)',
    'recommended_company_icon_size' => '(အကြံပြုထားသောအရွယ်အစား: ၅၀ x ၅၀ px)',
    'recommended_company_banner_size' => '(အကြံပြုထားသောအရွယ်အစား: ၁၉၂၀ x ၁၀၈၀ px)',
    'date_and_time_setting' => 'ရက်စွဲနှင့် အချိန်သတ်မှတ်ခြင်း',
    'currency_setting' => 'ငွေကြေးသတ်မှတ်ချက်',
    'back_to_multi_tenant' => 'အငှားများဆီသို့',
    'user_invitation_canceled' => 'အသုံးပြုသူ ဖိတ်ကြားချက်ကို ပယ်ဖျက်လိုက်ပါပြီ။',
    'notification_sent' => 'ပို့ခဲ့သည်',
    'created_by' => 'မှဖန်တီးသည်',

    // Supplier
    'supplier' => 'ပင်ရင်း(Supplier)',
    'supplier_no' => 'ပင်ရင်း(Supplier)မရှိပါ။',

    // Discount
    'individual' => 'သီးသန့်',
    'discount' => 'လျှော့ဈေး',
    'total_discount' => 'စုစုပေါင်းလျှော့ဈေး',
    'discount_on_products' => 'ထုတ်ကုန်များ၏လျှော့ဈေး',
    'discount_on_subtotal' => 'စုစုပေါင်းလျှော့ဈေး',
    'flat' => 'အခန်း',
    'discount_name' => 'လျှော့ဈေးအမည်',
    'discount_type' => 'လျှော့ဈေး အမျိုးအစား',
    'total_products' => 'ထုတ်ကုန်စုစုပေါင်း',
    'start_at' => 'စတင်သည်',
    'end_at' => 'ပြီးဆုံးသည်',
    'total_discount_on_products' => 'ထုတ်ကုန်များအတွက်စုစုပေါင်းလျှော့စျေး',
    'items_return_successfully' => 'ပစ္စည်းပို့ခြင်းအောင်မြင်သည်',
    'are_you_sure_to_active_this_discount' => 'ဈေးလျှော့မှာသေချာပြီလား?',
    'are_you_sure_to_de_active_this_discount' => 'လျှော့စျေးကို ဖွင့်ရန် သေချာသည်။',
    'selecting_products_with_ongoing_discounts_will_override_the_existing_discounts' => 'သင်၏ discont သည် ရွေးချယ်ထားသောပစ္စည်း၏ discont ရှိပါကပစ္စည်း discont ကို အစားထိုးသွားပါလိမ့်မည်။',
    'fixed_amounts_cannot_exceed_product_selling_prices' => 'ပုံသေပမာဏများသည် ကုန်ပစ္စည်းရောင်းဈေးထက် မကျော်လွန်နိုင်ပါ။',
    'add_discount' => 'ဈေးလျှော့ရန်',
    'flat_discount' => 'နောက်ဆုံးလျှော့ဈေး',
    'please_reduce_the_discount_amount' => 'လျှော့စျေးပမာဏကို လျှော့ချပါ။',
    'invalid_discount_amount' => 'လျှော့ဈေးပမာဏ မကိုက်ညီပါ',

    // customer group
    'the_customer_group_is_in_use' => 'ဝယ်ယူသူအဖွဲ့ အသုံးပြုနေပါသည်။',
    'this_group_will_be_selected_automatically_when_you_create_new_customer' => 'ဝယ်ယူသူအသစ်ကို သင်ဖန်တီးသောအခါ ဤအဖွဲ့ကို အလိုအလျောက်ရွေးချယ်ပါမည်။',

    // SMS setting
    'sms_setting' => 'Sms ဆက်တင်',
    'sms_send_from_name_or_phone_number' => 'အမည် သို့မဟုတ် ဖုန်းနံပါတ်မှ SMS ပေးပို့ရန်',
    'sms_driver' => 'Sms driver',
    'type_a_name_or_number_you_want_to_sent_sms_from' => 'SMS ပို့လိုသော အမည် သို့မဟုတ် ဖုန်းနံပါတ်ကို ရိုက်ထည့်ပါ။',
    'sms_content' => 'SMS အကြောင်းအရာ',
    'sms_content_message' => 'စာလုံးစုစုပေါင်း 160 သည် ကျွန်ုပ်၏ မက်ဆေ့ချ် တစ်ခုတည်းကိုသာ ပေးပို့ပါသည်။',
    'type_nexmo_key' => 'nexmo key ရိုက်ထည့်ပါ',
    'type_nexmo_secret_key' => 'nexmo လျှို့ဝှက် key ရိုက်ထည့်ပါ',
    'test_number' => 'နံပါတ်ကိုစစ်ဆေးရန်',
    'secret_key' => 'လျှို့ဝှက်key',
    'type_test_a_number' => 'စစ်ဆေးမည့်နံပါတ်ကို ရိုက်ထည့်ပါ။',
    'manage_branch' => 'ဆိုင်ခွဲကို စီမံပါ',
    'manage_branches' => ' ဆိုင်ခွဲများကို စီမံပါ။',
    'branches' => 'ဆိုင်ခွဲများ',
    'branch' => 'ဆိုင်ခွဲ',
    'location' => 'တည်နေရာ',
    'you_are_going_to_deactivate_a_branch' => 'သင်သည်ဆိုင်ခွဲတစ်ခုကို ပိတ်သိမ်းတော့မည်',
    'you_are_going_to_activate_a_branch' => 'သင်သည်ဆိုင်ခွဲတစ်ခုကို အသုံးပြုခွင့်ပေးမည်',
    'branch_&_counters' => 'ဆိုင်ခွဲ နှင့်ကောင်တာများ(counters)',
    'branch_&_warehouse' => 'ဆိုင်ခွဲနှင့် ဂိုဒေါင်(warehouse)',
    'branch_or_warehouse' => 'ဆိုင်ခွဲ/ဂိုဒေါင်(warehouse)',
    'branch_&_warehouses' => 'ဆိုင်ခွဲ နှင့် ဂိုဒေါင်များ( Warehouses)',
    'the_branch_is_in_use' => 'ဆိုင်ခွဲကိုအသုံးပြုနေပါသည်။',
    'main_branch_has' => 'ပင်မဌာနခွဲရှိသည်။',
    'data_able_status_filter_description' => 'Active သို့မဟုတ် Inactive ဖြစ်နေသော သင်၏ဒေတာဇယား (data table)ကို စစ်ထုတ်နိုင်ပါသည်။',

    // Counters
    'no_of_counters' => 'ကောင်တာများ မရှိပါ',
    'new_counter' => 'ကောင်တာအသစ်',
    'add_new_counter' => 'ကောင်တာအသစ်ထည့်ရန်',
    'sales_person' => 'အရောင်းဝန်ထမ်း',
    'you_are_going_to_deactivate_a_counter' => 'ကောင်တာတစ်ခုအားပိတ်သိမ်းမည်။',
    'you_are_going_to_activate_a_counter' => 'ကောင်တာတစ်ခုအသုံးပြုခွင့်ပေးမည်။',

    // Branch permission
    'view_branch' => 'ဆိုင်ခွဲများကို ကြည့်နိုင်ပါသည်။',
    'create_branch' => 'ဆိုင်ခွဲများကို ဖန်တီးနိုင်ပါသည်။',
    'update_branch' => 'ဆိုင်ခွဲများကို ပြောင်းလဲ(update)နိုင်သည်။',
    'delete_branch' => 'ဆိုင်ခွဲများကို ဖျက်သိမ်းနိုင်ပါသည်။',

    // Tax
    'taxes' => 'အခွန်ခများ',
    'all_taxes' => 'အခွန်ခများအားလုံး',
    'tax' => 'အခွန်',
    'tax_percentage' => 'အခွန်(%)',
    'percentage' => 'ရာခိုင်နှုန်း',
    'fixed' => 'သတ်မှတ်သည်။',
    'this_tax_will_be_applicable_automatically_when_tax_applied' => 'ဤအခွန်သည် အခွန်ကောက်ခံသည့်နေရာတွင် အလိုအလျောက် အကျုံးဝင်မည်ဖြစ်သည်။',

    // Tax permission
    'view_tax' => 'အခွန်များကိုကြည့်နိုင်ပါသည်၊၊',
    'create_tax' => 'အခွန်များကိုဖန်တီးနိုင်ပါသည်၊၊',
    'update_tax' => 'အခွန်များကိုပြောင်းလဲနိုင်ပါသည်၊၊',
    'delete_tax' => 'အခွန်များကိုဖျက်နိုင်ပါသည်၊၊',

    // POS/Booking Settings
    'pos_booking_settings' => 'POS/Booking Settings',
    'view_pos_booking_settings' => 'POS/Booking Settings ရွေးချယ်စရာများကိုကြည့်နိုင်ပါသည်။',
    'return_invoice' => 'ပြေစာပြန်ပေးသည်။',

    // Supplier permission
    'view_supplier' => 'ပင်ရင်းများ(supplier)ကို ကြည့်နိုင်ပါသည်။',
    'create_supplier' => 'ပင်ရင်းများ(supplier)ကို ဖန်တီးနိုင်ပါသည်။',
    'update_supplier' => 'ပင်ရင်းများ(supplier)ကို ပြောင်းလဲနိုင်ပါသည်။',
    'delete_supplier' => 'ပင်ရင်းများ(supplier)ကို ဖျက်နိုင်ပါသည်။',
    'change_status_supplier' => 'ပင်ရင်းများ(supplier)၏ အခြေနေ(status)ကိုပြောင်းလဲနိုင်ပါသည်။',

    // Payment Method
    'payment_note' => 'ပေးချေမှုမှတ်စု',
    'make_payment' => 'ပေးချေမှုကိုပြုလုပ်ပါ။',
    'payments' => 'ပေးချေမှုများ',
    'payment_methods' => 'ပေးချေနိုင်သောနည်းလမ်းများ',
    'payment_method' => 'ပေးချေနိုင်သောနည်းလမ်း',
    'payment_status' => 'ပေးချေနိုင်သောstatus',
    'payment_method_status' => 'ပေးချေနိုင်သောနည်းလမ်းများ၏status',
    'payment_type' => 'ပေးချေနိုင်သောအမျိူးအစား',
    'is_for_client' => 'Available to client',
    'rounded_to' => 'လုံးဝန်းရန်',
    'bank' => 'ဘဏ်',
    'bkash' => 'Bkash',
    'cash' => 'လက်ငင်း',
    'credit' => 'ခရစ်ဒစ်ကဒ်',
    'paypal' => 'Paypal',
    'stripe' => 'Stripe',
    'none' => 'မရှိပါ',
    'nearest_integer' => 'အနီးဆုံးကိန်းပြည့်',
    'nearest_half' => 'အနီးဆုံးတစ်ဝက်',
    'public_key' => 'Public Key',
    'client_id' => 'Client အိုင်ဒီ',
    'mode' => 'Mode',
    'live' => 'Live',
    'sandbox' => 'Sandbox',
    'make_paypal_payment' => 'Paypalဖြင့်ပေးချေမှုကိုပြုလုပ်ပါ။',
    'make_stripe_payment' => 'Stripeဖြင့်ပေးချေမှုကိုပြုလုပ်ပါ။',
    'pay_now' => 'ယခုပေးချေမည်။',

    // Payment Method
    'stripe_button' => 'Stripe ခလုတ်',
    'paypal_button' => 'Paypal ခလုတ်',
    'view_payment_method' => 'ပေးချေနိုင်သောနည်းလမ်းကိုကြည့်နိုင်ပါသည်။',
    'create_payment_method' => 'ပေးချေနိုင်သောနည်းလမ်းကိုဖန်တီးနိုင်ပါသည်။',
    'update_payment_method' => 'ပေးချေနိုင်သောနည်းလမ်းကိုပြောင်းလဲနိုင်ပါသည်။',
    'delete_payment_method' => 'ပေးချေနိုင်သောနည်းလမ်းကိုဖျက်နိုင်ပါသည်။',
    'enter_credit_card_information' => 'ခရစ်ဒစ်ကဒ်အချက်အလက်ကိုထည့်ပါ။',
    'card' => 'ကဒ်',
    'cheque' => 'စစ်ဆေးပါ။',

    // Import Customer
    'import_customers' => 'အရေးကြီးသော ဝယ်ယူသူများ',
    'export_customers' => 'ဝယ်ယူသူများကို တင်ပို့သည်။',
    'preview_import' => 'အစမ်းတင်သွင်းခြင်း',
    'filtered_customer' => 'စစ်ထုတ်ထားသော ဝယ်ယူသူများ',

    // Customer Csv format guideline
    'csv_download_label' => 'ကျွန်ုပ်တို့သည် သင့်အားနမူနာအဖြစ် .CSV ဖိုင်တစ်ခု ပေးလိုပါသည်။ ',
    'csv_format_guideline' => 'CSV ဖော်မတ်လမ်းညွှန်ချက်',
    'csv_guideline_1' => 'သင်၏ CSV ကို အောက်ပါနမူနာဖိုင်ကဲ့သို့ ပုံစံတူလုပ်ပါ။',
    'csv_guideline_1.5' => 'သင်၏ CSV ကော်လံများကို ဆီမီးကော်လံ (;) သို့မဟုတ် အခြားအက္ခရာများမဟုတ်ဘဲ ကော်မာများ (,) ဖြင့် ခွဲခြားထားသင့်သည်။',
    'csv_guideline_2' => 'သင်၏ CSV ရှိ ကော်လံအရေအတွက်သည် အောက်ပါဥပမာအတိုင်း ဖြစ်သင့်သည်။',
    'csv_guideline_3' => 'အကျုံးဝင်သောအကွက်များသည် စာလုံးအကြီးအသေးဖြစ်သည်၊ အကြံပြုချက်- အကွက်များ၏အမည်သည် အောက်ပါအတိုင်းဖြစ်ရမည်- အမည်၊ ကုန်ပစ္စည်းအမျိုးအစား၊ အရောင်း_စျေးနှုန်း၊ upc၊ မျိုးကွဲ_အမည် နှင့် မျိုးကွဲ_တန်ဖိုး။',
    'csv_guideline_product_group_field_name' => 'အကျုံးဝင်သော အကွက်များသည် စာလုံးအကြီးအသေးဖြစ်သည်၊ အကြံပြုချက်- အကွက်များ၏ အမည်သည် အောက်ပါအတိုင်း ဖြစ်ရမည်- အမည်ကို သေချာပါစေ။',
    'csv_guideline_4' => 'ကြီးမားသောဒေတာတင်သွင်းခြင်းအတွက် အကြံပြုချက်၊ သင်သည် သင်၏ဆာဗာလုပ်ဆောင်ချိန်နှင့် မှတ်ဉာဏ်ကန့်သတ်ချက်ကို တိုးမြှင့်ရန် လိုအပ်သည်။',
    'csv_guideline_5' => 'လိုအပ်သောအကွက်၏ (အမည်၊ ကုန်ပစ္စည်း_အမျိုးအစား၊ အရောင်း_စျေးနှုန်းနှင့် upc၊ ဤမျိုးကွဲထုတ်ကုန်များအတွက် ဤမျိုးကွဲ_အမည်နှင့် ဗားရှင်း_တန်ဖိုးများဘေးတွင် လိုအပ်သည်) ကော်လံဆဲလ်သည် ဗလာမဖြစ်ရပါ။',
    'csv_guideline_7' => 'အမှားအယွင်းတစ်ခုဖြစ်ပွားသည့်အခါ အမှားဖိုင်ကို ဒေါင်းလုဒ်လုပ်ကာ မှားယွင်းနေသောဆဲလ်များကို ပြုပြင်ပြီး ထိုဖိုင်ကို .csv ဖော်မတ်ဖြင့် ထပ်မံတင်သွင်းပါ။',



    // Import Supplier
    'import_suppliers' => 'ပင်ရင်းများ(supplier)ကို တင်သွင်းသည်။',
    'filtered_supplier' => 'စစ်ထုတ်ထားသော ပင်ရင်းများ(supplier)',
    'export_suppliers' => 'ပင်ရင်းများ(supplier)ကို တင်ပို့သည်။',

    // Sms Template
    'sms_template' => 'စာတို (Sms)ပုံစံ',
    'download' => 'ဒေါင်းလုဒ်',

    // Email Setup
    'wait_a_minute' => 'ခဏစောင့်ပါ',
    'popup_subtitle_for_redirect_notification_template' => 'ပြန်ညွှန်းရန် အသိပေးချက် နမူနာပုံစံအတွက် popup စာတန်း',
    'subject' => 'အကြောင်းအရာ',

    // Coupon
    'code' => 'Code (ကုဒ်)',
    'view_coupon' => 'ကူပွန်ကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_coupon' => 'ကူပွန်ကို ဖန်တီးနိုင်ပါသည်။',
    'update_coupon' => 'ကူပွန်ကို ပြောင်းလဲနိုင်ပါသည်။',
    'delete_coupon' => 'ကူပွန်ကို ဖျက်နိုင်ပါသည်။',
    'coupon' => 'ကူပွန်',

    // Counter
    'counter' => 'ကောင်တာ',

    // Order
    'export_order_list' => 'တင်ပို့မှု အမှာစာ စာရင်း',
    'order_list' => 'အမှာစာ စာရင်း',
    'sales_date' => 'ရောင်းသည့်ရက်',
    'total_amount' => 'စုစုပေါင်း ပမာဏ',
    'sub_total' => 'Sub-Total',
    'paid_amount' => 'ပေးချေသော ပမာဏ',
    'due_amount' => 'ပေးရမည့် ငွေပမာဏ',
    'due_receive' => 'လက်ခံရရှိခြင်း။',
    'total_orders' => 'စုစုပေါင်း အမှာစာ စာရင်း',
    'total_due' => 'စုစုပေါင်းပေးရမည့်',
    'due_payment_received' => 'ပေးချေမှုလက်ခံရရှိခဲ့သည်။',
    'no_orders_to_show' => 'ပြသရန် အမှာစာရင်း မရှိပါ။',

    // Contacts
    'phone_number(s)' => 'ဖုန်းနံပါတ်(များ)',

    // Setting
    'single_tax' => 'တစ်ခုတည်းသော အခွန်',
    'multi_tax' => 'အခွန်ပေါင်းစုံ',
    'group_by' => 'အုပ်စုလိုက်',
    'total_percentage_by_grouping_all_single_tax' => 'အခွန်တစ်ခုတည်းကို အုပ်စုဖွဲ့ခြင်းဖြင့် စုစုပေါင်း ရာခိုင်နှုန်း (%)',
    'the_tax_is_in_use' => 'အသုံးပြုနေသော အခွန်။',
    'switch' => 'ပြောင်းပါ။',

    // Address type
    'home' => 'အိမ်',
    'work' => 'အလုပ်အကိုင်',
    'office' => 'ရုံး',

    // Address
    'address_details_here' => 'ဒီမှာ လိပ်စာအသေးစိတ်',
    'add_more' => 'နောက်ထပ်ထည့်ပါ။',
    'address_title' => 'လိပ်စာ ခေါင်းစဉ်',
    'city' => 'မြို့',
    'zip_code' => 'Zip Code (ဇစ်ကုဒ်)',
    'address_details' => 'လိပ်စာ အသေးစိတ်',
    'select_country' => 'နိုင်ငံကို ရွေးချယ်ပါ',
    'add_address' => 'လိပ်စာ ပေါင်းထည့်ပါ။',
    'area' => 'ဧရိယာ (အကျယ်အဝန်း)',

    'email_s' => 'အီးမေးလ်(များ)',
    'contact_s' => 'အဆက်သွယ်(များ)',
    'phone_number_s' => 'ဖုန်း နံပါတ်(များ)',
    'address_s' => 'လိပ်စာ(များ)',
    'show_order_list' => 'မှာယူမှုစာရင်းကို ပြပါ။',

    'email_must_be_a_valid_email_address' => 'အီးမေးလ်အကွက်သည် မှန်ကန်သောအီးမေးလ်လိပ်စာ ဖြစ်ရမည်။',
    'title_field_is_required' => 'ခေါင်းစဉ်အကွက် လိုအပ်သည်။',
    'details_field_is_required' => 'အသေးစိတ်အကွက် လိုအပ်ပါသည်။',
    'choose_country' => 'နိုင်ငံကို ရွေးပါ။',
    'back_to_customers' => 'ဝယ်ယူသူများထံ ပြန်သွားရန်',

    // Product
    'products' => 'ထုတ်ကုန်များ',
    'product_list' => 'ကုန်ပစ္စည်းစာရင်း',
    'add_product' => 'ကုန်ပစ္စည်း ထည့်ပါ။',
    'product' => 'ထုတ်ကုန်',
    'selected_product' => 'ရွေးချယ်ထားသော ထုတ်ကုန်',
    'make_default' => 'ပုံသေလုပ်ပါ။',
    'edit_product' => 'ထုတ်ကုန်ကို တည်းဖြတ်ပါ။',
    'avg_purchase_price' => 'ပျမ်းမျှ ဝယ်ယူသော စျေးနှုန်း',
    'import_product' => 'သွင်းကုန်',
    'change_item_status' => 'ပစ္စည်း၏ status ကို ပြောင်းပါ။',
    'please_add_some_files_to_import' => 'တင်သွင်းရန် ဖိုင်အချို့ကို ထည့်ပါ။',
    'products_not_imported' => 'ကုန်ပစ္စည်းများ မတင်သွင်းပါ။',
    'partially_imported' => 'တစ်စိတ်တစ်ပိုင်းတင်သွင်းသည်။',
    'back_to_product' => 'ထုတ်ကုန်သို့ ပြန်သွားရန်',

    // Variations Attribute
    'variant_attributes' => 'ကွဲပြားသော အရည်အချင်းများ',
    'add_variant_attributes' => 'မူကွဲ Attributes (ဂုဏ်ရည်) များထည့်ပါ။',
    'export_all_data' => 'ဒေတာအားလုံးကို ထုတ်ယူပါ။',
    'attribute' => 'Attribute (ဂုဏ်ရည်)',
    'attributes' => 'Attributes (ဂုဏ်ရည်များ)',
    'view_attribute' => 'Attribute (ဂုဏ်ရည်) ကိုကြည့်ရှုနိုင်ပါသည်။',
    'create_attribute' => 'Attribute (ဂုဏ်ရည်) ကိုဖန်တီးနိုင်ပါသည်။',
    'update_attribute' => 'Attribute (ဂုဏ်ရည်) ကိုပြောင်းလဲနိုင်ပါသည်။',
    'delete_attribute' => 'Attribute (ဂုဏ်ရည်) ကိုဖျက်နိုင်ပါသည်။',
    'import_attribute' => 'Attribute (ဂုဏ်ရည်) ကို တင်သွင်းပါ။',
    'filtered_attributes' => 'စစ်ထုတ်ထားသော Attribute (ဂုဏ်ရည်)များ',
    'export_attributes' => 'Attribute (ဂုဏ်ရည်) ကို Export (တင်ပို့မှု) လုပ်နိုင်ပါတယ်။',
    'export_attribute' => 'Attribute (ဂုဏ်ရည်) ကို ထုတ်ယူပါ။',
    'download_attribute_data' => 'Attribute (ဂုဏ်ရည်) ဒေတာကို ဒေါင်းလုဒ်လုပ်ပါ။',
    'variations' => 'ပြောင်းလဲမှုများ',
    'import' => 'သွင်းကုန်',
    'variant_attribute' => 'မူကွဲ ရည်ညွှန်းချက်',
    'import_variant_attribute' => 'မူကွဲ Attribute (ဂုဏ်ရည်) ကို တင်သွင်းပါ။',
    'attribute_in_use' => 'အသုံးပြုနေသည့် Attribute (ဂုဏ်ရည်)',
    'variation_is_in_use' => 'အသုံးပြုမှုပုံစံကွဲလွဲမှု',
    'variant_default_success' => 'မူကွဲ၏ မူရင်း',
    'at_least_one_variant_should_available_for_each_product' => 'ထုတ်ကုန်တစ်ခုအတွက် အနည်းဆုံး မူကွဲတစ်ခု ရှိသင့်သည်။',


    // Brand
    'brands' => 'အမှတ်တံဆိပ်များ',
    'all_groups' => 'အဖွဲ့အားလုံး',
    'view_brand' => 'အမှတ်တံဆိပ်ကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_brand' => 'အမှတ်တံဆိပ်ကို ဖန်တီးနိုင်ပါသည်။',
    'update_brand' => 'အမှတ်တံဆိပ်ကို ပြောင်းလဲနိုင်ပါသည်။',
    'delete_brand' => 'အမှတ်တံဆိပ်ကို ဖျက်နိုင်ပါသည်။',
    'import_brand' => 'သွင်းကုန်အမှတ်တံဆိပ်',
    'filtered_brands' => 'စစ်ထုတ်ထားသော အမှတ်တံဆိပ်များ',
    'brand_in_use' => 'အသုံးပြုနေသော အမှတ်တံဆိပ်',
    'brand_name_a_z' => 'အမှတ်တံဆိပ် နာမည် : A-Z',
    'brand_name_z_a' => 'အမှတ်တံဆိပ် နာမည် : Z-A',

    // Unit
    'units' => 'Units(ယူနစ်များ)',
    'manage_units' => 'ယူနစ်များကို စီမံပါ။',
    'unit' => 'unit (ယူနစ်)',
    'add_unit' => 'unit (ယူနစ်) ထည့်ပါ။',
    'select_status' => 'အခြေအနေ (status)ကို ရွေးပါ။',
    'unit_name_is_required' => 'unit(ယူနစ်အမည်) လိုအပ်ပါသည်။',
    'save_unit' => 'unit(ယူနစ်) သိမ်းဆည်းပါ။',
    'unit_name_a_z' => 'unit(ယူနစ်အမည်) - A-Z',
    'unit_name_z_a' => 'unit(ယူနစ်အမည်) - Z-A',

    // Tax permission
    'view_unit' => 'units(ယူနစ်များ)ကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_unit' => 'units(ယူနစ်များ)ကို ဖန်တီးနိုင်သည်။',
    'update_unit' => 'units(ယူနစ်များ)ကို ပြောင်းလဲနိုင်ပါသည်။',
    'delete_unit' => 'units(ယူနစ်များ)ကို ဖျက်နိုင်သည်။',

    // Product Group
    'import_product_group' => 'သွင်းကုန်ထုတ်ကုန်အုပ်စု',
    'filtered_product_group' => 'စစ်ထုတ်ထားသော ထုတ်ကုန်အုပ်စု',
    'the_group_is_in_use' => 'အဖွဲ့ကို အသုံးပြုနေပါသည်။',

    // Group Permission
    'export_groups' => 'အဖွဲ့လိုက်တင်ပို့နိုင်သည်။',
    'download_group_data' => 'အဖွဲ့ဒေတာ(Group Data) ဒေါင်းလုဒ်လုပ်ပါ။',
    'view_group' => 'အဖွဲ့(Group)လိုက်ကြည့်ရှုနိုင်ပါသည်။',
    'create_group' => 'အုပ်စု(Group)ဖွဲ့နိုင်သည်။',
    'update_group' => 'အဖွဲ့(Group)ကို ပြောင်းလဲနိုင်ပါတယ်။',
    'delete_group' => 'အဖွဲ့(Group)ကို ဖျက်နိုင်သည်။',
    'import_group' => 'သွင်းကုန်အဖွဲ့',
    'export_group' => 'ပို့ကုန်အုပ်စု',

    // Sub Groups
    'sub_groups' => 'အဖွဲ့ခွဲများ',
    'sub_group' => 'အဖွဲ့ခွဲ',
    'view_sub_group' => 'အဖွဲ့ခွဲကို ကြည့်ရှုနိုင်ပါသည်။',
    'create_sub_group' => 'အဖွဲ့ခွဲကို ဖန်တီးနိုင်ပါသည်။',
    'update_sub_group' => 'အဖွဲ့ခွဲကို ပြောင်းလဲနိုင်ပါသည်။',
    'delete_sub_group' => 'အုပ်စုခွဲကို ဖျက်နိုင်ပါသည်။',
    'import_sub_groups' => 'တင်သွင်းသည့် အုပ်စုခွဲ',
    'export_sub_groups' => 'တင်ပို့သည့် အုပ်စုခွဲ',

    // Categories
    'export_categories' => 'အမျိုးအစားများကို တင်ပို့နိုင်သည်။',
    'categories' => 'အမျိုးအစားများ',
    'download_category_data' => 'အမျိုးအစားဒေတာကို ဒေါင်းလုဒ်လုပ်ပါ။',
    'import_category' => 'အမျိုးအစားကို တင်သွင်းပါ။',
    'import_categories' => 'အမျိုးအစားများကို တင်သွင်းပါ။',
    'category' => 'အမျိုးအစား',
    'filtered_category' => 'စစ်ထုတ်ထားသော အမျိုးအစား',
    'export_category' => 'အမျိုးအစားကို တင်ပို့ပါ။',
    'category_name_a_z' => 'အမျိုးအစားအမည်- A-Z',
    'category_name_z_a' => 'အမျိုးအစားအမည်- Z-A',
    'category_sub_category' => 'အမျိုးအစားခွဲ',
    'expandable_sub_category_table' => 'အမျိုးအစားခွဲများကို ချဲ့ထားသည်။',
    'add_sub_category' => 'အမျိုးအစားခွဲထည့်ပါ။',
    'category_in_use' => 'အသုံးပြုနေသောအမျိုးအစား',

    // Product Details
    'product_details' => 'ကုန်ပစ္စည်းအသေးစိတ်',
    'back_to_product_list' => 'ထုတ်ကုန်စာရင်းသို့ ပြန်သွားရန်',
    'back_to_product_details' => 'ထုတ်ကုန်အသေးစိတ်သို့ ပြန်သွားရန်',
    'single_product' => 'တစ်ခုတည်းသော ထုတ်ကုန်',
    'item_details' => 'အကြောင်းအရာအသေးစိတ်',
    'specifications' => 'သတ်မှတ်ချက်များ',
    'show_stock_overview' => 'ကုန်ပစ္စည်း ခြုံငုံသုံးသပ်ချက်ကို ပြပါ။',
    'stock_details' => 'ကုန်ပစ္စည်း အသေးစိတ်',
    'stock_adjust' => 'ကုန်ပစ္စည်း ညှိခြင်း',
    'sub-category' => 'အမျိုးအစားခွဲ',
    'sku' => 'SKU',
    'tax(%)' => 'အခွန်(%)',
    'warranty' => 'အာမခံ',
    'gallery' => 'ပြခန်း(Gallery)',
    'save_gallery' => 'ပြခန်း(Gallery)ကို သိမ်းဆည်းပါ။',
    'edit_gallery' => 'ပြခန်း(Gallery)ကို တည်းဖြတ်ပါ',
    'view_gallery' => 'ပြခန်း(Gallery)ကို ကြည့်ပါ။',
    'add_more_variant' => 'နောက်ထပ် မူကွဲကို ထည့်ပါ။',
    'variants' => 'မျိုးကွဲများ',

    // Inventory
    'inventory' => 'စာရင်း',
    'stock' => 'ကုန်ပစ္စည်း',
    'add_stock' => 'ကုန်ပစ္စည်း ထည့်ပါ။',
    'add_adjustment' => 'ညှိနှိုင်းခြင်း ထည့်ပါ။',///
    'adjustment' => 'ညှိနှိုင်းခြင်း',
    'addition' => 'ပေါင်းထည့်ခြင်း',
    'subtraction' => 'နုတ်ခြင်း။',
    'manage_lot' => 'ကုန်ပစ္စည်းအစုအဖွဲ့ကို စီမံပါ။',
    'lot' => 'ကုန်ပစ္စည်းအစုအဖွဲ့',
    'stock_adjustment' => 'ကုန်ပစ္စည်း ညှိနှိုင်းခြင်း',
    'stock' => 'ကုန်ပစ္စည်း',
    'import_stock' => 'ကုန်ပစ္စည်းကို တင်သွင်းပါ။',
    'print_bar_code' => 'ဘားကုဒ် ပုံနှိပ်(print)ရန်',
    'internal_transfer' => 'ပြည်တွင်း လွှဲပြောင်းမှု',
    'req._for_internal_transfer' => 'အတွင်းပိုင်းလွှဲပြောင်းမှုအတွက် တောင်းဆိုချက် ',
    'request_transfer' => 'လွှဲပြောင်းတောင်းဆိုခြင်း။',
    'cost_for_transfer' => 'လွှဲပြောင်းမှုအတွက်ကုန်ကျစရိတ်',
    'product_name_a_z' => 'ထုတ်ကုန်အမည်- A-Z',
    'product_name_z_a' => 'ထုတ်ကုန်အမည်- Z-A',
    'quantity_high_low' => 'ပမာဏ- မြင့်-နိမ့်',
    'quantity_low_high' => 'အရေအတွက်- အနိမ့်-မြင့်',
    'no_selling_price_added' => 'ရောင်းဈေးမထည့်ပါ။',
    'you_must_set_a_selling_price_to_activate_a_product' => 'ထုတ်ကုန်တစ်ခုကို အသုံးပြုရနိအတွက် အရောင်းစျေးနှုန်းတစ်ခု သတ်မှတ်ရပါမည်။',
    'please_select_products_to_transfer_first' => 'ဦးစွာလွှဲပြောင်းရန် ထုတ်ကုန်များကို ရွေးချယ်ပါ။',
    'please_enter_valid_unit_prices' => 'ကျေးဇူးပြု၍ တရားဝင်ယူနစ်စျေးနှုန်းများ ထည့်သွင်းပါ။',
    'please_input_reference_number_for_all_products' => 'ကျေးဇူးပြု၍ ထုတ်ကုန်အားလုံးအတွက် ရည်ညွှန်းနံပါတ်ကို ထည့်သွင်းပါ။',
    'reference_no' => 'အကိုးအကား အမှတ်',
    'order_status' => 'အမှာစာ (status)အနေအထား',
    'manage_users' => 'အသုံးပြုသူများကို စီမံခန့်ခွဲပါ။',
    'ref' => 'Ref',
    'total_unit' => 'စုစုပေါင်းယူနစ်',
    'view' => 'အမြင်',
    'grand_total_high_low' => 'စုစုပေါင်း း မြင့်-နိမ့်',
    'grand_total_low_high' => 'စုစုပေါင်း း အနိမ့်-အမြင့်',
    'select_product' => 'ထုတ်ကုန်ကိုရွေးချယ်ပါ။',
    'preview' => 'အစမ်း',
    'promotional_price' => 'ပရိုမိုးရှင်းစျေးနှုန်း',
    'stock_overview' => 'ကုန်ပစ္စည်း ခြုံငုံသုံးသပ်ချက်',
    'stock overview' => 'ကုန်ပစ္စည်း ခြုံငုံသုံးသပ်ချက်',
    'normal_internal_transfer_status_change_message' => 'အခြေအနေ(status)ကို ပြောင်းလဲလိုသည်မှာ သေချာပါသလား။',
    'completed_internal_transfer_status_change_message' => 'အခြေအနေ(status)ကို "ပြီးမြောက်သည်" သို့ ပြောင်းပါက၊ ၎င်းကို နောက်မှ ပြင်ဆင်၍မရပါ။',
    'status_complete' => 'ပြီးမြောက်သည်',
    'status_failed' => 'မအောင်မြင်ပါ။',

    'purchase_date' => 'ဝယ်ယူသည့်ရက်စွဲ',
    'purchase_status' => 'ဝယ်ယူမှုအခြေအနေ(status)',
    'select_purchase_status' => 'ဝယ်ယူမှုအခြေအနေ(status)ကို ရွေးချယ်ပါ။',
    'upload_csv_file' => 'CSV ဖိုင်ကို Uploadလုပ်ပါ။',
    'download_sample_file' => 'နမူနာဖိုင်ကို ဒေါင်းလုဒ်လုပ်ပါ။',
    'add_lot' => 'ကုန်ပစ္စည်းအစုအဖွဲ့ကို ထည့်ပါ။',
    'please_enter_products_to_store' => 'သိုလှောင်ရန် ထုတ်ကုန်များကို ထည့်သွင်းပါ။',
    'edit_lot' => 'ကုန်ပစ္စည်းအစုအဖွဲ့ကို တည်းဖြတ်မည်။',
    'view_lot_' => 'ကုန်ပစ္စည်းအစုအဖွဲ့ကို ကြည့်မည်။',
    'other_information' => 'အခြားအချက်အလက်',
    'other_charges' => 'အခြားသော အခကြေးငွေများ',
    'payment_summary' => 'ငွေပေးချေမှု အကျဉ်းချုပ်',
    'subtotal' => 'Subtotal',
    'total' => 'စုစုပေါင်း',
    'other_charge' => 'အခြားအခကြေးငွေ',

    //Stock Adjustment
    'select_an_adjustment_type' => 'ချိန်ညှိမှုအမျိုးအစားကို ရွေးပါ။',
    'stock_adjustment_only_possible_for_existing_products_in_stock' => 'လက်ကျန်ရှိပြီးသား ကုန်ပစ္စည်းများ အတွက်သာ ထုတ်ကုန်ချိန်ညှိမှုဖြစ်နိုင်သည်။',
    'please_select_products_for_adjustments_first' => 'ပြုပြင်ပြောင်းလဲမှုအတွက် ထုတ်ကုန်များကို ဦးစွာရွေးချယ်ပါ။',

    'stock_quantity' => 'ကုန်ပစ္စည်း အရေအတွက်',
    'unit_quantity' => 'ယူနစ် ပမာဏ',
    'last_update' => 'နောက်ဆုံးအပ်ဒိတ်',

    // Pos
    'biller' => 'ငွေပေးချေသူ',
    'pos' => 'POS',
    'pos_menu' => 'POS မီနူး',
    'sales_view' => 'အရောင်းအမြင်',
    'returns' => 'ပြန်လာသည်',
    'return' => 'ပြန်လာသည်',
    'partial' => 'တပိုင်းတစ',
    'all' => 'အားလုံး',
    'return_type' => 'စာပြန်ရိုက်ပါ။',
    'invoice_type_here' => 'ပြေစာအမျိုးအစားပါ။',
    'invoice' => 'ပြေစာ',
    'invoice_id' => 'ပြေစာ ID',
    'invoice_to' => 'ပြေစာပေး ဆီသို့',
    'invoice_from' => 'ပြေစာမှ',
    'sales_man' => 'အရောင်းဝန်ထမ်း',
    'unit_discount' => 'ယူနစ်လျှော့စျေး',
    'issue_date' => 'ထုတ်ပြန်ရက်စွဲ',
    'cash_counter' => 'ငွေသားကောင်တာ',
    'cash_opening_balance' => 'ဖွင့်ထားသော ငွေသားလက်ကျန်',
    'total_sales' => 'စုစုပေါင်းရောင်းအား',
    'total_expenses' => 'စုစုပေါင်းကုန်ကျစရိတ်',
    'total_cash_sales' => 'စုစုပေါင်းငွေရောင်းချမှု',
    'discount_on_total' => 'စုစုပေါင်းအပေါ်လျှော့စျေး',
    'please_enter_products_to_set_the_individual_discounts_to' => 'တစ်ဦးချင်းစီ လျှော့စျေး သတ်မှတ်ရန် ထုတ်ကုန်များကို ထည့်သွင်းပါ။',
    'invoice_total' => 'ပြေစာ စုစုပေါင်း',
    'payment_info' => 'ငွေပေးချေမှုအချက်အလက်',
    'total_paid' => 'စုစုပေါင်းပေးဆောင်မှု',
    'open_return_modal' => 'ပြန်ပေးသည့်ပုံစံကိုဖွင့်ပါ။',
    'open_hold_modal' => 'လက်ကိုင်ပုံစံဖွင့်ပါ။',
    'toggle_barcode_view' => 'ဘားကုဒ်မြင်ကွင်းကို ပြောင်းရန်',
    'select_page_style' => 'စာမျက်နှာစတိုင်ကို ရွေးပါ။',
    'done_payment' => 'ပေးချေမှုပြီးပါပြီ။',
    'add_payment' => 'ပေးချေမှုထည့်ပါ။',
    'hold_order_list' => 'အော်ဒါစာရင်းကို ကိုင်ထားပါ။',
    'discard_all_orders' => 'မှာယူမှုအားလုံးကို ဖျက်သိမ်းပါ။',
    'search_by_invoice_number' => 'ပြေစာနံပါတ်ဖြင့် ရှာဖွေပါ။',
    'are_you_sure_you_want_to_discard_all_orders' => 'မှာယူမှုအားလုံးကို ဖျက်သိမ်းလိုသည်မှာ သေချာပါသလား။',
    'keep' => 'သိမ်းဆည်းပါ။',
    'discard' => 'ပယ်ဖျက်သည်။',
    'no_items_to_show' => 'ပြရန်အကြောင်းအရာမရှိပါ။',
    'close_cash_register' => 'ငွေရှင်းကောင်တာပိတ်ပါ။',
    'expected_closing_amount' => 'မျှော်မှန်းထားသော အပိတ်ပမာဏ',
    'closing_amount' => 'အပိတ်ပမာဏ',
    'opening_amount' => 'အဖွင့်ပမာဏ',
    'opening_balance' => 'အဖွင့်လက်ကျန်',
    'closing_balance' => 'စာရင်းပိတ်လက်ကျန်',
    'close_register' => 'ကောင်တာပိတ်သည်။',
    'cash_in_hand' => 'လက်ထဲရှိ ငွေသား',
    'cash_sales' => 'ငွေသားအရောင်း',
    'cheque_sales' => 'အရောင်းစစ်ဆေးပါ။',
    'total_cash' => 'စုစုပေါင်းငွေ',
    'counter_name' => 'ကောင်တာအမည်',
    'opened_at' => ' ဖွင့်လှစ်ခဲ့သည်။',
    'closed_at' => ' ပိတ်သည်။',
    'register_details' => 'ကောင်တာအသေးစိတ်',
    'credit_sales' => 'Credit ရောင်းသည်။',
    'are_you_sure_you_want_to_clear_the_cart' => 'လှည်းကို ရှင်းပစ်ချင်သည်မှာ သေချာပါသလား?',
    'no_items_to_sell' => 'ရောင်းစရာပစ္စည်းမရှိ။',
    'stock_out' => 'ကုန်ပစ္စည်း မရှိပါ။',
    'no_more_items_in_stock' => 'ကုန်ပစ္စည်း မရှိတော့ပါ။!',
    'specified_quantity_unavailable_in_stock' => 'သတ်မှတ်ထားသော ပမာဏကို ကုန်ပစ္စည်းတွင် မရရှိနိုင်ပါ။',
    'already_in_cart' => 'ဈေးလှည်းထဲ ရောက်နေပြီးပါပြီ။',
    'select_cash_register' => 'ငွေသားကောင်တာကို ရွေးပါ။',
    'back_to_dashboard' => 'Dashboard သို့ ပြန်သွားရန်',
    'open_a_cash_register' => 'ငွေရှင်းကောင်တာဖွင့်ပါ။',
    'opened_by' => 'ဖွင့်လှစ်ခဲ့သည်။',
    'select_branch_or_warehouse' => 'ဌာနခွဲ သို့မဟုတ် ဂိုဒေါင်ကို ရွေးပါ။',
    'cannot_deactivate_the_current_branch' => 'လက်ရှိဌာနခွဲကို ဖျက်၍မရပါ။',
    'select_a_branch_or_a_warehouse' => 'ဌာနခွဲတစ်ခု သို့မဟုတ် သိုလှောင်ရုံတစ်ခုကို ရွေးချယ်ပါ။',
    'cannot_switch_branches_while_a_cash_register_is_open' => 'ငွေရှင်းကောင်တာဖွင့်ထားချိန်တွင် အခွဲအများကို မပြောင်းနိုင်ပါ။',
    'item_not_in_stock_in_current_branch' => 'လက်ရှိအခွဲတွင် ကုန်ပစ္စည်းမကျန်ပါ။',
    'item_not_found' => 'ပစ္စည်းမတွေ့ပါ။',
    'stock_out_message' => '{product_name} ပစ္စည်းမရှိတော့ပါ။ ရရှိနိုင်သောပမာဏ{available_qty}',
    'select_unit_price' => 'ယူနစ်စျေးနှုန်းကိုရွေးချယ်ပါ။',
    'select_date' => 'ရက်စွဲကို ရွေးပါ။',

    // Expense
    'expenses' => 'အသုံးစရိတ်များ',
    'expense' => 'အသုံးစရိတ်',
    'area_of_expense' => 'အသုံးစရိတ်ဧရိယာ',
    'expense_date' => 'ကုန်ကျစရိတ်ရက်စွဲ',
    'attachments' => 'ချိတ်ဆက်မှု',
    'total_expense_in_this_area' => 'ဤဧရိယာ၌စုစုပေါင်းကုန်ကျစရိတ်',

    // Setting
    'tax_management' => 'အခွန်စီမံခန့်ခွဲမှု',
    'please_select_a_tax' => 'အခွန်တစ်ခုရွေးပါ။',
    'please_set_a_default_tax_from_settings' => 'ကျေးဇူးပြု၍ ဆက်တင်များမှ ပုံသေအခွန်ကို သတ်မှတ်ပါ။',
    'branch_and_counters' => 'အခွဲနှင့်ကောင်တာများ',
    'branch_and_warehouse' => 'အခွဲနှင့် ဂိုဒေါင်',
    'branchOrWarehouse' => 'အခွဲ သို့မဟုတ် ဂိုဒေါင်',
    'pos_settings' => 'POS ဆက်တင်များ',
    'sub_categories' => 'အမျိုးအစားခွဲများ',
    'in_use' => '{field} အသုံးပြုနေပါသည်။',
    'sub_category' => 'အမျိုးအစားခွဲ',
    'import_sub_category' => 'အမျိုးအစားခွဲများကို တင်သွင်းပါ။',
    'export_sub_category' => 'အမျိုးအစားခွဲကို တင်ပို့ပါ။',
    'sales_invoice_already_configured' => 'အရောင်းပြေစာအား ပြင်ဆင်ပြီးဖြစ်သည်။',
    'return_invoice_already_configured' => 'ပြေစာပြန်ပို့ရန် စီစဉ်ပြီးဖြစ်သည်။',

    'amount' => 'ပမာဏ',
    'description' => 'ဖော်ပြချက်',
    'add_to_report' => 'အစီရင်ခံစာသို့ထည့်ပါ။',
    'max' => 'အများ',
    'min' => 'အနည်း',
    'export_brand' => 'အမှတ်တံဆိပ်တင်ပို့သည်၊၊',
    'download_data' => ' {name} ၏ဒေတာကို ဒေါင်းလုဒ်လုပ်ပါ။',

    // Unit
    'export_unit' => 'unit (ယူနစ်) တင်ပို့သည်။',

    // Export Heading
    'id' => 'Id',
    'created_at' => 'ဖန်တီးခဲ့သည်။',

    'allowed_file_types' => 'ခွင့်ပြုထားသောဖိုင်အမျိုးအစားများ- jpeg၊ jpg၊ png၊ pdf၊ csv၊ xls၊ xlsx၊ docs',
    'allowed_file_types_xls_excluded' => 'ခွင့်ပြုထားသောဖိုင်အမျိုးအစားများ- jpeg၊ jpg၊ png၊ pdf၊ csv၊ docs',
    'allowed_file_types_xls_csv_excluded' => 'ခွင့်ပြုထားသော ဖိုင်အမျိုးအစားများ- jpeg၊ jpg၊ png၊ pdf၊ docs',
    'allowed_file_types_csv' => 'ခွင့်ပြုထားသော ဖိုင်အမျိုးအစားများ- CSV',
    'allowed_file_types_for_product' => 'ခွင့်ပြုထားသော ဖိုင်အမျိုးအစားများ- jpeg၊ jpg၊ png',
    'attachment_validation_message' => 'ပူးတွဲပါဖိုင်များသည် jpeg၊ jpg၊ png၊ pdf၊ csv၊ xls၊ xlsx၊ docs',
    'attachment' => 'ချိတ်ဆက်မှု',
    'has_been_imported_successfully' => 'ဖိုင်ကို အောင်မြင်စွာ ထည့်သွင်းပြီးပါပြီ။',

    // Product
    'attribute_variant' => 'Attribute(ဂုဏ်ရည်) ကွဲပြားမှု',
    'back_to_products' => 'ထုတ်ကုန်စာမျက်နှာသို့ ပြန်သွားရန်',
    'products_import' => 'ထုတ်ကုန်များတင်သွင်းသည်။',
    'please_select_a_product_to_view_stock_data' => 'စတော့ဒေတာကိုကြည့်ရှုရန် ထုတ်ကုန်တစ်ခုကို ရွေးချယ်ပါ။',
    'view_product_stocks' => 'ထုတ်ကုန်ကို ကြည့်ပါ။',
    'export_filtered_data' => 'စစ်ထုတ်ထားသောဒေတာကို ထုတ်ယူပါ။',
    'type_of_product' => 'ထုတ်ကုန်အမျိုးအစား',
    'no_of_variants' => 'မျိုးကွဲမရှိပါ။',
    'tags' => 'Tags',
    'product_active' => 'ထုတ်ကုန်ကို အောင်မြင်စွာ အသုံးပြုနိုင်ပါပြီ။',
    'variant' => 'မူကွဲ',
    'single' => 'တစ်ခုတည်း',
    'product_type' => 'ထုတ်ကုန်အမျိုးအစား',
    'product_name' => 'ထုတ်ကုန်အမည်',
    'variant_thumbnail' => 'မူကွဲ ပုံသေး',
    'add_to_inventory' => 'စာရင်းထဲသို့ထည့်ပါ။',
    'avg_unit_price' => 'ပျမ်းမျှ တစ်ခုချင်းစျေးနှုန်း',
    'selling_price' => 'ရောင်းဈေး',
    'sales_price' => 'အရောင်းစျေးနှုန်း',
    'you_are_going_to_activate_a_product' => 'သင်သည် ထုတ်ကုန်တစ်ခုကို အသုံးပြုတော့မည်ဖြစ်သည်။',
    'you_are_going_to_deactivate_a_product' => 'သင်သည် ထုတ်ကုန်တစ်ခုကို ပိတ်ပစ်တော့မည်။',
    'product_pricing' => 'ထုတ်ကုန်စျေးနှုန်း',
    'profit_margin' => 'အမြတ်အစွန်း',
    'numeric' => 'ဂဏန်း',
    'received' => 'ရရှိခဲ့သည်။',
    'pending' => 'ဆိုင်းငံ့ထားသည်။',
    'complete' => 'ပြီးမြောက်သည်။',
    'failed' => 'မအောင်မြင်ပါ။',
    'canceled' => 'ဖျက်သိမ်းလိုက်သည်။',


    'sticker' => 'စတစ်ကာ',

    'how_to_manage_product' => 'ထုတ်ကုန်ကို ဘယ်လိုစီမံခန့်ခွဲမလဲ။',
    'product_instruction_1' => '- ထုတ်ကုန်ခေါင်းစဉ်၊ ဖော်ပြချက်၊ သတ်မှတ်ချက်များ၊ ထုတ်ကုန် SKU၊ အခွန်နှင့် ထုတ်ကုန်မျိုးကွဲများကဲ့သို့သော အခြေခံအချက်အလက်များဖြင့် ထုတ်ကုန်တစ်ခုကို ထည့်ပါ။',
    'product_instruction_2' => '- ထုတ်ကုန် တစ်ခုကို ဖန်တီးပြီးသည်နှင့် ၎င်းကို ဆိုင်ခွဲများအားလုံးမှ ကြည့်ရှုနိုင်မည်ဖြစ်ပါသည်။ သို့သော် သီးခြားဆိုင်ခွဲတစ်ခုတွင် ကုန်ပစ္စည်းမရှိပါက ဆိုင်ခွဲသည် ကုန်ပစ္စည်းကို ရောင်းချနိုင်မည်မဟုတ်ပေ။',
    'product_instruction_3' => '- စျေးနှုန်း၊ ဘားကုဒ်၊ လျှော့စျေး၊ အခွန်စသည်ဖြင့် ကုန်ပစ္စည်းများ၏ အခြားအချက်အလက်များကို စီမံခန့်ခွဲပါ။ ',
    'product_instruction_4' => '- မော်ဂျူး ထုတ်ကုန်ကို သီးခြား ဆိုင်ခွဲတစ်ခုက စီမံခန့်ခွဲသည်။ သီးခြားဆိုင်ခွဲတစ်ခုသို့ သီးခြား Lot ပေါင်းထည့်ခြင်းဖြင့် စတော့ကို စီမံခန့်ခွဲပါ။',
    'product_instruction_5' => '- စတော့တစ်ခုကို လက်ခံရရှိပြီးနောက် (status- လက်ခံထားသည်)၊ ထိုထုတ်ကုန်များသည် သင့်စတော့တွင် အလိုအလျောက် ပေါင်းထည့်မည်ဖြစ်သည်။',

    'what_is_an_individual_discount' => 'တစ်ဦးချင်းလျှော့စျေးဆိုတာဘာလဲ။',
    "discounts_on_individual_products_only_have_an_impact_on_each_variant's_unit_pricing" => "ထုတ်ကုန်တစ်ခုချင်းစီအပေါ် လျှော့စျေးများသည် အမျိုးအစားတစ်ခုစီ၏ ယူနစ်စျေးနှုန်းအပေါ်တွင်သာ သက်ရောက်မှုရှိသည်။",
    'user_deactivated' => 'အသုံးပြုသူအား ပိတ်ထားသည်။',
    'user_activated' => 'အသုံးပြုသူ ပါဝင်လာပါပြီ။',

    //    Variant
    'variant_name' => 'မူကွဲအမည်',
    'image' => 'ပုံ',
    'upload_file' => 'ဖိုင်ကို တင်ပါ။',
    'warranty_duration' => 'အာမခံကာလ',
    'description_here' => 'ဤနေရာတွင် ဖော်ပြချက် ',
    'variant_in_use' => 'မူကွဲအသုံးပြုမှု',
    'you_are_going_to_deactivate_a_variant' => 'သင်သည် မူကွဲတစ်ခုကို ပိတ်သွားပါမည်။',
    'you_are_going_to_activate_a_variant' => 'သင်သည် မူကွဲတစ်ခုကို အသုံးပြုစေတော့မည်။',
    'warranty_duration_type' => 'အာမခံကာလ အမျိုးအစား',


    'product_information' => 'ထုတ်ကုန် သတင်းအချက်အလက်',
    'specification' => 'သတ်မှတ်ချက်',
    'attribute_definition' => 'Attribute အဓိပ္ပါယ်',
    'variant_product' => 'မူကွဲထုတ်ကုန်',
    'search_and_select' => ' {name}ကို ရှာဖွေပြီး ရွေးချယ်ပါ။',
    'choose_branch' => 'ဆိုင်ခွဲကို ရွေးပါ။',
    'hour_s' => 'နာရီ(များ)',
    'day_s' => 'နေ့(များ)',
    'month_s' => 'လ(များ)',
    'year_s' => 'နှစ်(များ)',
    'select_field_name' => ' {name}ကို ရွေးချယ်ပါ။',
    'item_details_of_variant' => 'မူကွဲ၏ အသေးစိတ်အချက်များ',
    'enter_sku' => 'skuကို ထည့်ပါ။',
    'product_gallery' => 'ထုတ်ကုန်ပြခန်း',
    'product_status' => 'ထုတ်ကုန်အခြေအနေ',
    'product_filters' => 'ထုတ်ကုန် စစ်ထုတ်မှုများ',
    'recommended_type_jpg' => '(အကြံပြုထားသော အမျိုးအစား .jpg)',
    'max_filesize_5mb' => 'အများဆုံးဖိုင်အရွယ်အစား- 5MB',
    'variant_gallery' => 'မူကွဲပြခန်း',
    'allowed_file_types_for_variant' => 'ခွင့်ပြုထားသော ဖိုင်အမျိုးအစားများ- jpeg၊ jpg၊ png',
    'variant_details' => 'မူကွဲအသေးစိတ်',
    'variant_details_has_been_added_successfully' => 'မူကွဲအသေးစိတ်များကို အောင်မြင်စွာ ထည့်သွင်းပြီးပါပြီ။',
    'low_stock_reminder_quantity' => 'အရေအတွက်နည်းသော ကုန်ပစ္စည်း သတိပေးချက််',
    'stock_reminder_quantity' => 'ကုန်ပစ္စည်း သတိပေးချက် အရေအတွက်',
    'please_specify_a_stock_reminder_quantity' => 'ကျေးဇူးပြု၍ ကုန်ပစ္စည်းသတိပေးချက် ပမာဏကို သတ်မှတ်ပါ။',
    'error' => 'အမှား!',
    'required_fields_are_missing' => 'လိုအပ်သော အကွက်များ လွဲချော်နေပါသည်။',
    'missing_fields' => 'လွဲချော်နေသော အကွက်များ',
    'errors_found' => 'အမှားများတွေ့ရှိသည်',
    'export_report.xlsx' => 'report.xlsx ကို ထုတ်ယူပါ။',
    'successful_rows' => 'အောင်မြင်သောအတန်း(row)များ',
    'unsuccessful_rows' => 'မအောင်မြင်သောအတန်း(row)များ',
    'low_stock_reminder_(LSR)' => 'ကုန်ပစ္စည်းနည်းသော သတိပေးချက် (LSR)',
    'tax_/_vat' => 'အခွန်/ Vat',
    'unit_tax' => 'ယူနစ်ခွန်',
    'unit_tax_percentage' => 'ယူနစ်ခွန် (%)',
    'quantity' => 'အရေအတွက်',
    'get_a_new_sku' => 'SKU အသစ်တစ်ခုရယူပါ။',
    'get_a_new_upc' => 'UPC အသစ်တစ်ခုရယူပါ။',
    'product_upc' => 'ထုတ်ကုန် UPC',
    'the_upc_you_entered_is_not_unique' => 'သင်ထည့်သွင်းထားသော UPC သည် သီးသန့်မဟုတ်ပါ။',/////
    'add_new' => '{name}အသစ်တစ်ခု ပေါင်းထည့်ပါ။',
    'add_new_' => 'အသစ်ထည့်ပါ။',
    'remove_variant_attribute' => 'မူကွဲ attribute ကို ဖယ်ရှားပါ။',
    'clicking_remove_file_will_remove_the_image_indefinitely' => '"ဖိုင်ကိုဖယ်ရှားရန်" ကိုနှိပ်ခြင်းဖြင့် ပုံကို အကန့်အသတ်မရှိ ဖယ်ရှားပါမည်။',
    'clicking_remove_file_will_remove_the_attachment_permanently' => '"ဖိုင်ကိုဖယ်ရှားရန်" ကိုနှိပ်ခြင်းဖြင့် ပူးတွဲပါဖိုင်ကို အပြီးတိုင်ဖယ်ရှားပါမည်။!',
    'attribute_variation' => 'attribute ကွဲလွဲမှု',
    'variant_not_added_yet' => 'မူကွဲကို မထည့်ရသေးပါ။',
    'add_more_variants' => 'နောက်ထပ်မူကွဲများကို ထည့်ပါ။',
    'product_in_use' => 'အသုံးပြုနေသောထုတ်ကုန်',
    'upc' => 'UPC',
    'note' => 'မှတ်စု',
    'add_note' => 'မှတ်စုထည့်ပါ။',

    // Time - picker input
    'am' => 'မနက်',
    'pm' => 'ည',

    //Lot
    'Lot' => 'ကုန်ပစ္စည်းအစုအဖွဲ့',
    'sales' => 'အရောင်း',/////Sales
    'sale_price' => 'ရောင်းဈေး',
    'price' => 'စျေးနှုန်း',
    'lot_reference_number' => 'ကုန်ပစ္စည်းအစုအဖွဲ့ကိ၏ ရည်ညွှန်းနံပါတ်',

    //Stock
    'purchase_price' => 'ဝယ်ယူသောစျေးနှုန်း',
    'unit_price' => 'တစ်ခုချင်းစျေးနှုန်း',
    'total_price' => 'စုစုပေါင်းစျေးနှုန်း',
    'manufacturing_date' => 'ထုတ်လုပ်သည့်ရက်စွဲ',
    'expire_date' => 'သက်တမ်းကုန်ဆုံးရက်',
    'bar_code' => 'ဘားကုဒ်',
    'tax_type' => 'အခွန်အမျိုးအစား',
    'exclusive' => 'သီးသန့်',
    'inclusive' => 'ပါဝင်ပါသည်။',
    'arrival_date' => 'ဆိုက်ရောက်မည့်ရက်',
    'received_at' => 'မှာ လက်ခံခဲ့သည်။',
    'received_by' => 'မှ ရရှိခဲ့သည်။',
    'stock_available' => 'ကုန်ပစ္စည်း ရရှိနိုင်ပါသည်။',
    'view_stock_overview' => 'ကုန်ပစ္စည်း ခြုံငုံသုံးသပ်ချက်ကို ကြည့်ပါ။',

    //Warehouse
    'warehouse' => 'ဂိုဒေါင်',
    'warehouse_/_branch' => 'ဂိုဒေါင်/ဆိုင်ခွဲ',
    'branch_/_warehouse' => 'ဆိုင်ခွဲ/ဂိုဒေါင်',
    'warehouse_/_store_to' => 'ဂိုဒေါင်/ဆိုင်ခွဲသို့',
    'warehouse_/_store_from' => 'ဂိုဒေါင်/ဆိုင်ခွဲများမှ',
    'store' => 'စတိုး',
    'stock_transfer' => 'ကုန်ပစ္စည်း လွှဲပြောင်းသည်။',
    'receive_product' => 'ထုတ်ကုန်ကိုလက်ခံပါ။',
    'branch_stock' => 'ဆိုင်ခွဲရှိကုန်ပစ္စည်း',
    'warehouse_stock' => 'ဂိုဒေါင်ရှိ ကုန်ပစ္စည်း',
    'lot_list' => 'ကုန်ပစ္စည်းအစုအဖွဲ့စာရင်း',
    'select_lot' => 'ကုန်ပစ္စည်းအစုအဖွဲ့ကို ရွေးချယ်ပါ။',
    'lot_number' => 'ကုန်ပစ္စည်းအစုအဖွဲ့၏ နံပါတ်',
    'print_barcode' => 'ဘားကုဒ်ကို ပုံနှိပ်(ပရင့်)ထုတ်ပါ။',
    'page_style' => 'စာမျက်နှာစတိုင်လ်',
    'generate_barcode' => 'ဘားကုဒ်ကို ဖန်တီးပါ။',
    'generate_qrcode' => 'QR ကုဒ်ကို ဖန်တီးပါ။',
    'print_qrcode' => 'qrcode ကို ပုံနှိပ်(ပရင့်)ထုတ်ပါ။',
    'print_order' => 'ပုံနှိပ်(ပရင့်) အမှာစာ',
    'print' => 'ပုံနှိပ်(ပရင့်)',
    'import_warehouse_stock' => 'ဂိုဒေါင်ရှိကုန်ပစ္စည်း တင်သွင်းပါ။',

    // Group
    'total_items' => 'စုစုပေါင်းပစ္စည်းများ',
    'add_items' => 'ပစ္စည်းများထည့်ပါ။',
    'group_name_a_z' => 'အဖွဲ့အမည်- A-Z',
    'group_name_z_a' => 'အဖွဲ့အမည်- Z-A',
    'total_items_high_low' => 'စုစုပေါင်းပစ္စည်းများ- မြင့်-နိမ့်',
    'total_items_low_high' => 'စုစုပေါင်းပစ္စည်းများ- နိမ့်-မြင့်',
    'most_recent' => 'လတ်တလော',
    'last_created' => 'နောက်ဆုံးဖန်တီးခဲ့သည်။',

    // Brand
    'brand_name' => 'အမှတ်တံဆိပ်အမည်',
    'brand_description' => 'အမှတ်တံဆိပ်ဖော်ပြချက်',
    'change_brand_logo' => 'အမှတ်တံဆိပ်လိုဂိုကို ပြောင်းပါ။',
    'add_products_here' => 'ထုတ်ကုန်များကို ဤနေရာတွင် ထည့်ပါ။',
    'subcategory' => 'အမျိုးအစားခွဲ',

    // status change modal
    'are_you_sure_you_want_to_change_the_status' => 'အခြေအနေကို ပြောင်းလဲလိုသည်မှာ သေချာပါသလား။',
    'normal_lot_status_change_message' => 'အခြေအနေကို ပြောင်းလဲလိုသည်မှာ သေချာပါသလား။',
    'delivered_lot_status_change_message' => 'အခြေအနေကို "ပေးပို့သည်" သို့ ပြောင်းပါက၊ ၎င်းကို နောက်မှ ပြင်ဆင်၍မရပါ။',
    'delivered_status_not_allowed_to_change' => "ပေးပို့ထားသော အခြေအနေအား ပြောင်းလဲခွင့်မပြုပါ။",
    'delivered_lot_not_allowed_to_delete' => "ပေးပို့ထားသော ကုန်ပစ္စည်းအစုအဖွဲ့များကို ဖျက်ခွင့်မပြုပါ။",
    'delivered_lot_not_allowed_to_update' => "ပေးပို့ထားသော ကုန်ပစ္စည်းအစုအဖွဲ့များကို ပြောင်းလဲခွင့်မပြုပါ။",
    'completed_internal_transfer_not_allowed_to_update' => "ပြီးမြောက်သွားသော အတွင်းလွှဲပြောင်းလဲမှုကို ပြောင်းလဲခွင့်မပြုပါ။",
    'completed_internal_transfer_not_allowed_to_delete' => "ပြီးဆုံးသွားသော အတွင်းပိုင်းလွှဲပြောင်းမှုကို ဖျက်ခွင့်မပြုပါ။",
    'internal_transfer_only_possible_for_existing_variant_in_stock' => 'စတော့ရှယ်ယာရှိ ရှိပြီးသားမူကွဲအတွက်သာ ပြည်တွင်းငွေလွှဲမှုဖြစ်နိုင်သည်။',
    'lot_reference_no' => 'ကုန်ပစ္စည်းအစုအဖွဲ့၏ ကိုးကားနံပါတ်',

    // payment
    'mixed' => "ရောနှော",
    'hold' => "လက်ရှိ",/////
    'status_due' => "ပေးရသည်။",
    'total_payable' => "ပေးဆောင်နိုင်သော စုစုပေါင်း",
    'total_paying' => "စုစုပေါင်းပေးဆောင်ခြင်း",
    'change_return' => "ပြန်ပြောင်းပါ။",
    'due' => "ပေးရသည်။",
    'add_new_payment_method' => 'ငွေပေးချေမှုနည်းလမ်းအသစ်ကို ထည့်ပါ။',
    'select_tax' => 'အခွန်ရွေးပါ။',
    'search_by_invoice_id' => 'ငွေတောင်းခံလွှာ ID ဖြင့်ရှာဖွေပါ။',
    'search_invoice' => 'ပြေစာရှာပါ။',
    'held_at' => 'တွင် ကျင်းပခဲ့သည်။',/////
    'clear_all_items' => 'ပစ္စည်းအားလုံးကို ရှင်းလင်းပါ။',
    'invoices' => 'ပြေစာများ',

    //Discount
    'customer_name' => 'ဝယ်ယူသူအမည်',
    'add_return' => 'ပြန်ထည့်ပါ။',
    'pcs' => 'pc(များ)',
    'total_items_returned' => 'စုစုပေါင်းပစ္စည်းများ ပြန်လည်ပေးအပ်ခဲ့သည်။',
    'return_total' => 'စုစုပေါင်း ပြန်ပို့ပါ။',
    'total_return' => 'ပြန်လာသော စုစုပေါင်း',
    'return_quantity' => 'ပမာဏကို ပြန်ပေးပါ။',
    'return_subtotal' => 'subtotal ကို ပြန်ပေးပါ။',
    'return_note' => 'မှတ်စုစာ ပြန်ပါ',

    //Invoice template
    'indepandent_chips' => 'သီးခြားချစ်ပ်များ(chips)',
    'table_chips' => 'စားပွဲတင်ချစ်ပ်များ(Table chips)',
    'sales_report' => 'အရောင်းအစီရင်ခံစာ',
    'sales_return_report' => 'အရောင်းပြန်လည်တင်ပြခြင်း။',


    //Report
    'order' => 'အော်ဒါ',
    'ordered_at' => 'မှာကြားတယ်။',
    'export' => 'တင်ပို့ခြင်း။',
    'sold_by' => 'ဖြင့်ရောင်းချသည်။',
    'return_by' => 'ဖြင့် ပြန်ရန်',
    'tax_amount' => 'အခွန်ပမာဏ',
    'grand_total' => 'စုစုပေါင်း',
    'stock_worth' => 'ကုန်ပစ္စည်းတန်ဖိုး',
    'paid' => 'ပေးချေခဲ့သည်။',
    'total_tax' => 'စုစုပေါင်းအခွန်',
    'total_sales_amount' => 'စုစုပေါင်းရောင်းရငွေပမာဏ',
    'download_sales_data' => 'အရောင်းဒေတာကို ဒေါင်းလုဒ်လုပ်ပါ။',
    'export_sales_report' => 'အရောင်းအစီရင်ခံစာ တင်ပို့ပါ။',
    'export_all_order' => 'အော်ဒါအားလုံး တင်ပို့ပါ။',
    'export_all_return_order' => 'ပြန်လာသော အော်ဒါအားလုံး တင်ပို့ပါ။',

    'other_cost' => 'အခြားကုန်ကျစရိတ်',
    'reports' => 'အစီရင်ခံစာများ',
    'lot_report' => 'ကုန်ပစ္စည်းအစုအဖွဲ့ အစီရင်ခံစာ',
    'stock_report' => 'ကုန်ပစ္စည်း အစီရင်ခံစာ',
    'total_purchase' => 'စုစုပေါင်းဝယ်ယူမှု',
    'supplier_report' => 'ပင်ရင်း(supplier)ကို အစီရင်ခံစာ',
    'supplier_address' => 'ပင်ရင်း(supplier) လိပ်စာ',
    'select_supplier' => 'ပင်ရင်း(supplier)ကို ရွေးချယ်ပါ။',
    'customer_report' => 'ဝယ်ယူသူအစီရင်ခံစာ',
    'available_qty' => 'ရရှိနိုင်သောပမာဏ',
    'discount_amount' => 'လျှော့စျေး',
    'total_purchase_amount' => 'စုစုပေါင်းဝယ်ယူမှုပမာဏ',

    //Dashboard
    'highlight' => 'အထူးဖော်ပြမှု',
    'filter' => 'စစ်ထုတ်မည်(filter)',
    'weekly' => 'အပတ်စဉ်',
    'monthly' => 'လစဉ်',
    'yearly' => 'နှစ်အလိုက်',
    'last_week' => 'ပြီးခဲ့သောအပတ်',
    'this_week' => 'ဒီအပတ်',
    'last_month' => 'ပြီးခဲ့သောလ',
    'this_month' => 'ဒီလ',
    'this_year' => 'ဒီနှစ်',
    'last_year' => 'လွန်ခဲ့တဲ့နှစ်',
    'stock_summary' => 'ကုန်ပစ္စည်း အနှစ်ချုပ်',
    'view_all_invoices' => 'ပြေစာအားလုံးကို ကြည့်ရှုပါ။',
    'view_all_customers' => 'ဝယ်ယူသူအားလုံးကို ကြည့်ရှုပါ။',
    'view_all_stocks' => 'ကုန်ပစ္စည်းအားလုံးကို ကြည့်ရှုပါ။',
    'sales_and_purchase' => 'အရောင်းနှင့်အဝယ်',
    'top_selling_products' => 'အရောင်းရဆုံးထုတ်ကုန်များ',
    'top_selling_product_report' => 'အရောင်းရဆုံးထုတ်ကုန်အစီရင်ခံစာ',
    'export_all' => 'အားလုံးကို တင်ပို့ပါ။',
    'expense_report' => 'ကုန်ကျစရိတ်အစီရင်ခံစာ',
    'user_report' => 'အသုံးပြုသူအစီရင်ခံစာ',
    'user_details_report' => 'အသုံးပြုသူအသေးစိတ် အစီရင်ခံစာ',
    'total_sale_return' => 'စုစုပေါင်းရောင်းရငွေ',
    'sale_return' => 'ပြန်ရောင်းသည်။',
    'total_internal_transfer' => 'စုစုပေါင်းအတွင်းပိုင်းလွှဲပြောင်းသည်။',
    'total_transfer_cost' => 'စုစုပေါင်းလွှဲပြောင်းမှု ကုန်ကျစရိတ်',
    'total_adjustment' => 'စုစုပေါင်းညှိနှိုင်းမှု',
    'export_all_user' => 'အသုံးပြုသူအားလုံးကို ထုတ်ယူပါ။',
    'warehouse_report' => 'ဆိုင်ခွဲ/ဂိုဒေါင်',
    'warehouse_report_export' => 'ဆိုင်ခွဲ/ဂိုဒေါင် တင်ပို့ခြင်း။',
    'total_order' => 'အော်ဒါစုစုပေါင်း',
    'total_adjustments' => 'စုစုပေါင်း ညှိုနှိုင်းမှုများ',
    'total_return_order' => 'ပြန်စာစုစုပေါင်း',
    'total_sold_amount' => 'စုစုပေါင်းရောင်းရငွေပမာဏ',
    'profit_loss' => 'အမြတ်အရှုံး',
    'profit_loss_report' => 'အမြတ်အရှုံး အစီရင်ခံစာ',
    'choose_filter_group' => 'စစ်ထုတ်သည့်အဖွဲ့ကို ရွေးပါ။',
    'choose_year' => 'ခုနှစ်ကို ရွေးပါ။',
    'profit_amount' => 'အမြတ်ငွေပမာဏ',
    'total_sell_amount' => 'စုစုပေါင်းရောင်းရငွေပမာဏ',
    'net_profit' => 'အသားတင်အမြတ်',
    'cash_counter_report' => 'ငွေရှင်းကောင်တာ',
    'cash_counter_report_export' => 'အစီရင်ခံစာထုတ်ပါ။',
    'difference' => 'ကွာခြားချက်',
    'sale_amount' => 'အရောင်းပမာဏ',
    'export_all_profit_loss' => 'အမြတ်-အရှုံး ကို ပို့ပါ',
    'account_sid' => 'အကောင့်နံပတ်',
    'auth_token' => 'အထောက်အထားအမှတ်အသား',
    'sms_sent_from' => 'မှ စာတို (sms)ပို့သည်',
    'auto_send_sms' => 'အလိုအလျောက် စာတို (sms) ပို့ပါ။',
    'sorry_this_item_has_dependent_entity' => 'ဝမ်းနည်းပါတယ်၊ ဤပစ္စည်းတွင် မှီခိုမှုတစ်ခုရှိနေပါသည်။',
    'add_template' => 'ပုံစံ(template)ထည့်ပါ။',
    'branch_warehouse' => 'ဆိုင်ခွဲ ဂိုဒေါင်',
    'select_branch' => 'ဆိုင်ခွဲကို ရွေးပါ။h',
    'content' => 'အကြောင်းအရာ',
    'thanks_for_shopping_from_us_please_come_again' => 'ဒီကနေ စျေးဝယ်ပေးလို့ ကျေးဇူးတင်ပါတယ်။',
    'message' => 'သတင်းစကား(message)',
    'textarea_placeholder' => 'ဧရိယာ နေရာယူသူ',


    'jan' => 'ဇန်နဝါရီ',
    'feb' => 'ဖေဖော်ဝါရီ',
    'mar' => 'မတ်',
    'apr' => 'ဧပြီ',
    'may' => 'မေ',
    'jun' => 'ဇွန်',
    'jul' => 'ဇူလိုင်',
    'aug' => 'ဩဂုတ်',
    'sep' => 'စက်တင်ဘာ',
    'oct' => 'အောက်တိုဘာ',
    'nov' => 'နိုဝင်ဘာ',
    'dec' => 'ဒီဇင်ဘာ',


], include 'custom.php');
